Step2 리뷰요청 드립니다.
next-step/jpa-query-builder pull request #1
Opened 2023-06-11 15:19 UTC by jwee0330

안녕하세요.
일단 빠르게 구현해 보았습니다.
피드백 받으면서 좀 더 고도화 해보도록 하겠습니다.

2023-06-13 09:00 UTC, liquidjoo requested changes
2단계 고생하셨습니다
정원님 코드를 보고 새로운 시야로 볼 수 있어서 너무 좋았습니다 👍 
몇 가지 코멘트 남겼습니다
확인하고 다시 요청 주세요 🙇

2023-06-13 17:02 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/DefaultJavaToSqlColumnParser.java
> +public class DefaultJavaToSqlColumnParser {
[3d54d31](https://github.com/next-step/jpa-query-builder/pull/1/commits/3d54d3124640710a92e9166eb12443ebdd4e9b7a)
수정하면서 parser 도 테스트 코드 추가 했습니다!

2023-06-13 17:07 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/collection/IdGeneratedValueStrategyMap.java
> +public class IdGeneratedValueStrategyMap {
[171c6c2](https://github.com/next-step/jpa-query-builder/pull/1/commits/171c6c21a7a926c6a191f25b62ce17a3dd51e79e)
간단하게 추가해 보았습니다.
나중에 generatedStrategy 도 dialect 에 따라서 바뀔걸 생각하니 아찔하네요 ^^;;

2023-06-13 17:09 UTC, jwee0330 commented
객체간 책임이 약간 모호한것 같아서 전체적으로 리팩터링 해보았습니다.

parse 는 dialect 를 주입받아 dialect 에 맞는 타입으로 변환해주는 역할만 갖고
자바 타입이 어떤 타입으로 매핑되어 있어야 하는지는 dialect 의 구현이 갖고 있도록 수정해 봤습니다.

2023-06-14 15:33 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/DdlQueryBuilder.java
> +        }
제가 빌더패턴에 익숙하지 않아서 코멘트를 남겼었는데요~
저의 개인적인 생각은 builder 패턴에서의 build 와 생성자에서 초기화 및 유효성을 검증하는 부분이 따로 있어서 궁금증이 생긴 것 같았고 익숙하지 않아서 코멘트를 남기게 되었습니다!
빌더패턴에서 빌드 메서드 호출 시 검증하는 로직이 포함이 되어도 괜찮을까요..?
> 단순히! 궁금해서 물어보는 것입니다!!

2023-06-14 15:37 UTC, liquidjoo approved these changes
피드백 반영 너무 좋았습니다!!
외부 주입을 통해 구현 코드를 다르게 가져갈 수 있는 부분도 인상이 깊었습니다. 👍 
다음 단계 진행해 주세요 🙇

2023-06-14 15:37 UTC, liquidjoo commented on src/test/java/persistence/sql/ddl/DdlQueryBuilderTest.java
> +                .isEqualTo("create table users (id bigint auto_increment,nick_name varchar(255) null,old int null,email varchar(255) not null, constraint pk_person primary key (id));");
assertAll() 에 대해서 공부하는 겸! 사용해 보아도 좋을 것 같아요!
assertAll 와 assertThat 을 여러개 사용할 때의 차이도 알면 좋습니다

2023-06-14 15:37 UTC, merged