Step3: QueryBuilder DML
next-step/jpa-query-builder pull request #176
Opened 2024-02-20 14:01 UTC by nainu

3단계 변경 PR입니다.

이렇게 저렇게 고치다 보니 변경이 많습니다. 크게는
- (Insert/Select/SelectOne/Delete)QueryBuilder 들이 추가되었습니다.
- QueryBuilder 에서 로직을 별도로 뜯어내면서 QueryBuilder.java 자체는 사이즈가 줄었습니다.(ddl/dml 모두)
- step2 에 리뷰로 남겨주셨던 코멘트도 반영하였습니다.
  - EntityColumn 이란 이름으로 컬럼정보를 뽑아냈던 객체가 리뷰처럼 IColumn 인터페이스로 바뀌어서 util.column 패키지에 자리잡았습니다.
  - MySQL 타입 컨버팅은 enum 으로 변경했더니 코드가 더 복잡해져서, 일단은 현재 구조로 유지해 봅니다.

코드가 많아지니 버벅버벅 하면서도 테스트코드 덕분에 막 뜯어 고치고 있습니다 ㅎㅎ
미리 리뷰 감사드려요. 이전처럼 많은 피드백 부탁드립니다.

2024-02-21 12:25 UTC, jinyoungchoi95 requested changes
안녕하세요 동윤님 😄

3단계도 잘 구현해주셨네요. 다음 단계 넘어가기전 개선하면 좋을 만한 부분 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/dml/SelectOneQueryBuilder.java
> +                .collect(Collectors.joining(", "));
요런 부분도 메소드로 분리하면 가독성이 더 올라갈 것 같아요 :)

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/dml/SelectQueryBuilder.java
> +        return "SELECT " + fieldsForSelecting + " FROM " + tableName;
`String.format`과 `+` 연산 중 동윤님은 어떤걸 선호하시나요 ? 👀

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/util/EntityClassInspector.java
> +        }
```suggestion
        if (isId) {
            boolean autoIncrement = isAutoIncrement(generatedValueAnnotation);
            return new PrimaryKeyColumn(columnName, type, columnLength, autoIncrement);
        }
        boolean nullable = isNullable(columnAnnotation);
        return new GeneralColumn(columnName, type, columnLength, nullable);
```
👀

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/util/EntityClassInspector.java
> +    public Stream<IColumn> getColumns() {
`Stream` 반환에 대해서는 제공하는 method는 사용하는 쪽에 일관적인 결과를 제공하지 못한다는 단점이 있는데요. 동윤님은 어떻게 생각하세요?

https://www.baeldung.com/java-return-stream-collection

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/dml/InsertQueryBuilder.java
> +    private final Map<String, Object> valueMap;
여기서도 insert 쿼리를 생성할때마다 builder를 생성하는 것이 아닌 하나의 entityClass에 대해 query를 생성하는 정보를 가지고, `valueMap`을 파라미터로 받아 동적으로 쿼리를 생성하는건 어떨까요?

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/dml/DeleteQueryBuilder.java
> +        });
stream의 처리에 대해서 forEach를 사용한다면 가독성이 오를 수 있지만, 현재와 같이 결과를 만드는 경우에는 filter와 map을 적절히 사용해서 처리하는 것이 더 가독성이 좋을 것 같아요. 

https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/

stream foreach를 종단 연산에서 사용하는 것은 안티패턴이기도해요.
> Terminal operations, such as Stream.forEach or IntStream.sum, may traverse the stream to produce a result or a side-effect. After the terminal operation is performed, the stream pipeline is considered consumed, and can no longer be used; if you need to traverse the same data source again, you must return to the data source to get a new stream. In almost all cases, terminal operations are eager, completing their traversal of the data source and processing of the pipeline before returning. Only the terminal operations iterator() and spliterator() are not; these are provided as an "escape hatch" to enable arbitrary client-controlled pipeline traversals in the event that the existing operations are not sufficient to the task.

https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/ddl/QueryBuilder.java
>  public class QueryBuilder {
`QueryBuilder`는 싱글톤 객체여도 좋을 것 같네요 :)

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/main/java/database/sql/Util.java
> +public class Util {
유틸클래스라면 생성자를 private으로 막는게 좋을 것 같아요. 테스트도 추가해주세요 :)

2024-02-21 12:25 UTC, jinyoungchoi95 commented on src/test/java/database/sql/dml/QueryBuilderTest.java
> +class QueryBuilderTest {
좀더 테스트 단위를 세분화해서 테스트 작성해주시면 좋을 것 같아요. (ex. `PrimaryKeyColumn.toColumnDefinition()`, `각 QueryBuilder.builderQuery()`)

뒤로갈수록 각각의 클래스들이 유기적으로 결합하기 때문에 리팩터링하거나 기능 추가요소가 매우 많기 때문에 아직 초반인 지금 단계에서 각 클래스 단위별 테스트를 만들어두는게 후반에 fail 포인트를 찾기가 쉬워 마음을 안정시켜줍니다 😃

2024-02-22 08:41 UTC, nainu commented on src/main/java/database/sql/util/column/GeneralColumn.java
> +    }
훨씬 좋네요! :) 변경했습니다.

2024-02-22 08:42 UTC, nainu commented on src/main/java/database/sql/util/column/IColumn.java
> +public interface IColumn {
Column 으로 변경했습니다. jakarta.persistence.Column 와 사용이 겹치는 클래스가(`EntityClassInspector`) 있는데, 명시적으로 `jakarta.persistence.Column` 를 쓰도록 했습니다. 별로 지저분해지지는 않는 것 같아요.

2024-02-22 08:45 UTC, nainu commented on src/main/java/database/sql/util/column/PrimaryKeyColumn.java
> +    }
아래 방식으로 변경했다가, StringJoiner 라는 걸 발견해서 아래처럼 변경했습니다.
```
StringJoiner definitionJoiner = new StringJoiner(" ");
definitionJoiner.add(columnName);
definitionJoiner.add(typeConverter.convert(type, columnLength));
if (autoIncrement) {
    definitionJoiner.add("AUTO_INCREMENT");
}
definitionJoiner.add("PRIMARY KEY");
return definitionJoiner.toString();
```
여러 용도로 사용할 수 있을 것 같아요. 성급할 수도 있지만 여기저기 바꿔봤습니다 ㅎㅎ

2024-02-22 08:48 UTC, nainu commented on src/main/java/database/sql/util/type/MySQLTypeConverter.java
> +public class MySQLTypeConverter implements TypeConverter {
오 저도 이 지저분함을 어떻게 해결할까 하다가 hibernate 코드를 보니 Dialect 라는게 있더라구요. 이 개념이 지금 바로 차용해도 되는건지 고민하다가 나중에 다시 생각하자 했었던것 같아요. 
커넥션을 생성하는 단계쯔음, 굉장히 초기단계에 dialect 가 결정되기 때문에 저 위쪽까지 끌어 올려서 주입받아 사용해도 될 것 같기도 해요. 일단은 그랬습니다. :)
요약 설명 감사합니다.

2024-02-22 08:50 UTC, nainu commented on src/main/java/database/sql/dml/SelectOneQueryBuilder.java
> +        EntityClassInspector inspector = new EntityClassInspector(entityClass);
:+1: 이 방식으로 변경하면서, 각 쿼리빌더들의 생성자로 로직이 많이 모이고, 코드가 조금 더 깔끔해졌습니다. :)

2024-02-22 08:53 UTC, nainu commented on src/main/java/database/sql/dml/InsertQueryBuilder.java
> +    private final Map<String, Object> valueMap;
반영했습니다. 많이 깔끔해졌어요!

2024-02-22 08:54 UTC, nainu commented on src/main/java/database/sql/dml/DeleteQueryBuilder.java
> +        });
이 문서들과 위 java-return-stream-collection 문서를 보고 나서 Stream 으로 주고받던 부분들 그리고 .stream() 을 쓰던 부분까지 정리해버렸습니다.
써서 얻는 장점이 별로 없고, 없앴더니 오히려 더 읽기 좋아졌습니다. :+1: :+1: :+1:

2024-02-22 08:55 UTC, nainu commented on src/main/java/database/sql/util/EntityClassInspector.java
> +    public Stream<IColumn> getColumns() {
https://github.com/next-step/jpa-query-builder/pull/176#discussion_r1497432512
요기 함께 코멘트 남깁니다.

2024-02-22 08:57 UTC, nainu commented on src/main/java/database/sql/Util.java
> +public class Util {
:+1::+1::+1: 요거 자꾸 잊네요. README.md 에도 적어놨습니다. ㅎㅎ
```
## 커밋 전에 확인할 것

...
* 생성자에 접근자를 잘 적용했나?
...
```

2024-02-22 08:59 UTC, nainu commented on src/test/java/database/sql/dml/QueryBuilderTest.java
> +class QueryBuilderTest {
QueryBuilderTest 는 가지고 있는 메서드들을 간략히 테스트하고, 여기 있던 테스트들은 *QueryBuilderTest 로 내려보냈습니다.
상대적으로 낮은 추상단계에서 테스트하는게 변경에 방해가 된다는 생각이 있었는데, 잘 응집돼있는 상태에서는 꼭 그렇지 않다는 느낌이 들었습니다.
:+1::+1::+1:

2024-02-22 09:01 UTC, nainu commented on src/main/java/database/sql/util/EntityClassInspector.java
> +        }
:+1:
```
## 커밋 전에 확인할 것

...
* else 키워드를 줄여보기
...
```
메모완료....

2024-02-22 09:02 UTC, nainu commented on src/main/java/database/sql/dml/SelectQueryBuilder.java
> +        return "SELECT " + fieldsForSelecting + " FROM " + tableName;
상황에따라, 인데요. 그래도 동일한 레벨에선 동일한 방식을 써야 할 것 같다는 생각이 들었어요.
대부분 String.format 을 활용하도록 변경했습니다.

2024-02-22 09:03 UTC, nainu commented on src/main/java/database/sql/dml/SelectOneQueryBuilder.java
> +                .collect(Collectors.joining(", "));
:+1:
요 코멘트를 보고, EntityClassInspector 에 메서드 몇개를 더 추가하면서 Column 을 아예 감추고, 여러 코드가 정리됐어요.!

2024-02-22 09:04 UTC, nainu commented
리뷰 남겨주신 내용 확인하고 반영했습니다. 많이 배우고 있습니다. 🙇  감사합니다. ^^
리뷰할 때 어떤 방식이 편하실지 잘 몰라서 resolve 는 직접 하지 않았습니다.

2024-02-22 14:39 UTC, jinyoungchoi95 commented on src/main/java/database/sql/util/column/IColumn.java
> +public interface IColumn {
아 `jakarta.persistence.Column`를 쓰는 곳이 있었군요 😢 

`EntityColumn`과 같은 네이밍은 어떠세요? 사실 현재의 구조상 어쩔수없는 일이어서 `IColumn`도 나쁘지 않다고 다시 생각이 드네요 🤔

2024-02-22 14:40 UTC, jinyoungchoi95 commented on src/main/java/database/sql/util/column/PrimaryKeyColumn.java
> +    }
충분히 좋은 것 같습니다 👍

2024-02-22 14:40 UTC, nainu commented on src/main/java/database/sql/util/column/IColumn.java
> +public interface IColumn {
일단 EntityColumn 으로 변경해볼게요. 밖에서 참조하는 곳도 없어서 이름이 좀 길어져도 괜찮을 것 같아요.

2024-02-22 15:12 UTC, merged