[Step3 - QueryBuilder DML] 김현태 미션 제출합니다.
next-step/jpa-query-builder pull request #180
Opened 2024-02-21 12:57 UTC by Hyunta

안녕하세요 태화님!
DML 미션을 하면서 DDL 쪽 리팩터링을 좀 진행하였습니다.
DDL 쿼리에 종속적인 도메인들을 만들다 보니 DML 에서 재사용할 때 문제가 되었습니다.

DDL 쿼리 생성과 관련된 책임들은 `sql/ddl ` 하위 QueryBuilder로 옮겼고,
Table, Column 같은 도메인들은 DDL, DML 관련된 내용을 모르도록 설계를 조금 변경했습니다.

이번 단계도 잘 부탁드립니다!

2024-02-22 06:48 UTC, wooobo requested changes
안녕하세요 현태님!

3단계 잘 진행해주셨습니다~ 👏 
몇가지 코멘트 남겨놓았는데 확인 후 재요청 부탁드려요~

눈이 많이 왔네요~ 눈길 조심하세요~

2024-02-22 06:48 UTC, wooobo commented on src/main/java/persistence/sql/domain/IdColumn.java
> +    public boolean isAutoIncrement() {
`isAutoIncrement` 메소드와 같은 특정 클래스의 성격에서만 정의하는것이 생긴다면 저는 상속을 안할 것 같아요. 다른 성격의 객체가 아닐까 생각이들어서요. 

개인적으론 현재 시점에서는  `Column`객체와 합성을 고려해보거나 추상화하지 않을것 같은데. 현태님은 어떻게 생각하시나요~?

2024-02-22 13:01 UTC, Hyunta commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +                column.getType().getTypeQuery() +
점을 하나만 찍으라고 하는 이유는
객체에게 값을 물어와서 외부에 로직을 노출시키지 말고, 
메세지를 통해서 책임을 분리하기 위함이라고 생각됩니다.

아래 내용과 함께 반영하도록 하겠습니다.

2024-02-22 13:13 UTC, Hyunta commented on src/main/java/persistence/sql/domain/DataType.java
>          return START_SYMBOL + defaultValue + END_SYMBOL;
DataType에서 EnumMap<Dialect,String> 으로 Dialect 에 맞는 타입으로 반환할 수 있도록 수정했습니다!
추가로 한줄에 점 하나만 찍기를 지키려고 선언하는 부분을 분리하였습니다.
이렇게  구현하면 여러 Dialect에 대해서 처리할 수 해당 Enum으로 처리할 수 있습니다.

2024-02-22 13:23 UTC, Hyunta commented on src/main/java/persistence/sql/domain/IdColumn.java
> +    public boolean isAutoIncrement() {
저도 사실 확신이 서지는 않습니다.
처음에 상속받는 구조로 했던 이유는 `Insert` 구문을 만들 때 Id의 구조만 달라서 였습니다.

두가지 방안이 떠올랐습니다.
1. IdColumn와 List<FieldColumn> 별도로 관리
2. Column 으로 상속받는 IdColumn, FieldColumn 구현체

제가 2번을 선택한 이유는 Insert 구문을 만들 때
Id 따로 Field 따로 만들어서 합치는 과정이 오히려 복잡해질 것이라 생각했습니다.
1,2번 둘다 각각 트레이드오프가 있다고 생각하는데 저는 iteration의 간결화와 Table 에서 컬럼 내용들을 한번에 관리하기 위해서 2번을 선택했습니다.

2024-02-23 04:02 UTC, wooobo approved these changes
안녕하세요 현태님!

코멘트에 대해 함께 고민해주셔서 감사합니다! 👍 
3단계도 역시 잘진행해주셨습니다~

이번과정에서 다형성과 추상화를 잘 사용하는 부분도 중요한 부분이라고 생각하는데요!
추상화시 읽어 보면 좋을것같은 내용 공유해봅니다~
[Premature Abstraction](https://injulkarnilesh.github.io/design-principles/PREMATURE_ABSTRACTION/)

그럼 다음단계도 기대하겠습니다!
좋은 하루 되세요~

2024-02-23 04:02 UTC, merged

2024-02-23 10:59 UTC, Hyunta commented on src/main/java/persistence/sql/domain/IdColumn.java
> +        return generationType.equals(GenerationType.IDENTITY);
좋은 지적 감사합니다, 저도 태화님 의견에 동의 합니다!
반영하도록 하겠습니다ㅎㅎ

2024-02-23 11:17 UTC, Hyunta commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +                columnType.getDataTypeForDialect(Dialect.H2) +
저도 Builder를 만들고 나서 사용할 때 clazz를 미리 주입받는게 재사용하기에 불편하더라구요.
고쳐야겠다고 생각을 하면서도 시간이 없다는 핑계로 미루고 있었는데 마침 이 부분을 딱 피드백 주셔서 수정하도록 하겠습니다.👍🏻

싱글톤 객체도 고민해봤지만, CreateQueryBuilder는 Dialect를 필드값으로 가지고 있어서 기존 구조대로 staticMethod를 호출하도
록 하는게 일관성이 있어보여서 유지하도록 하겠습니다!