[Step2 - QueryBuilder DDL] 윤주리 미션 제출합니다.
next-step/jpa-query-builder pull request #182
Opened 2024-02-21 15:02 UTC by jurlring

성주님 안녕하세요? 오랜만이죠? 하하 
평일에 하는게 확실이 쉽지 않네요..

`1차 리뷰신청은 쉽게 생각해서 보내기` 를 이번에도 실천해서 PR 보냅니다 ㅎ.ㅎ

[간단 설계 요약]
1. column type 같이 이미 정해진 값은 enum으로 만들어보았어요.
2. table는 class name, columns, idColumn을 가져요. 제가 DDL 만드는 기준으로 정해보았어요.
3. column은 name, type, length, generatedValueStrategy, nullable 값을 가져요. 이것도 제가 DDL 만드는 기준으로 정해보았어요.
4. 다른 DB에도 붙일 수 있게 인터페이스로 table과 column을 만들고 구현체로 MySQL DDL을 만들 수 있도록 구현했어요.

개떡같은 코드지만 성주님은 찰떡같이 봐주시면 감사하겠습니다!! 
저도 너드해지고 싶어요!! 찰진 리뷰 부탁드려용!! 감사합니다?

2024-02-22 08:59 UTC, liquidjoo requested changes
안녕하세요 주리님 :)
2단계 미션 잘 해주셨어요 👍 
몇 가지 코멘트 남겼습니다~ 확인하고 다시 요청 주세요 🙇 
궁금한 사항들은 언제든 DM 주세요

2024-02-22 08:59 UTC, liquidjoo commented on README.md
> +## 🚀 2단계 - QueryBuilder DDL
요구사항 정리 👍

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/ColumnType.java
> +public enum ColumnType {
Mysql 이 아니라 다른 데이터베이스에 대한 확장성을 고려했을 때
어떻게 설계를 해볼 수 있을까요?

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/GenerationTypeStrategy.java
> +    IDENTITY("AUTO_INCREMENT"),
IDENTITY 일 때 AUTO 와 중복이 되는 것 같은데요~

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/MySqlColumn.java
> +    private final String name;
name, length 를 원시 값을 포장해 객체화 한다면 어떤 장점이 있을까요?

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/MySqlColumn.java
> +    }
많은 책임이 있는 것 같은데요~ 위의 코멘트를 통해 역할을 적절히 나누어보면 좋을 것 같아요 :)

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/MySqlColumn.java
> +    }
getGeneratedValueStrategyDefinition 의 책임이 어디에 있는 것이 좋을까요?

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/MySqlDDLGenerator.java
> +        MySqlTable table = MySqlTable.from(entity);
메서드로 책임을 나누는 것도 좋지만 역할을 나누어 볼까요?

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/MySqlTable.java
> +    private final Field idColumn;
idColumn 또한 하나의 Column 이라 볼 수 있지 않을까요?

2024-02-22 08:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/MySqlTable.java
> +    }
역할을 나누었을 때 어떤 장점을 갖고 있을까요?

2024-02-22 11:50 UTC, jurlring commented on src/main/java/persistence/sql/ddl/MySqlColumn.java
> +    private final String name;
원시값을 검증하는 역할이 옮겨지겠네용~~
그럼 테스트가 용이하고, Column클래스의 가독성도 좋아질 것 같아용~~
요녀석들 수정하겠습니당~

2024-02-22 13:36 UTC, jurlring commented on src/main/java/persistence/sql/ddl/MySqlColumn.java
> +    }
흠~~ 필드에 있어도 될거 같기도 하네요~~ create 쿼리를 어떻게 만드느냐에 따라 다를 것 같아용~

2024-02-22 15:03 UTC, jurlring commented on src/main/java/persistence/sql/ddl/GenerationTypeStrategy.java
> +    IDENTITY("AUTO_INCREMENT"),
MySQL에서는 IDENTITY 일 때 AUTO 일 때 모두 AUTO_INCREMENT로 기본키 생성하는 것으로 알고 있어서 같은 값을 썼어요

2024-02-22 16:18 UTC, jurlring commented on src/main/java/persistence/sql/ddl/MySqlTable.java
> +    }
[이 리뷰](https://github.com/next-step/jpa-query-builder/pull/182#discussion_r1498886770)와 이어지는 리뷰가 맞을까요?
그렇다면 역할을 나누는 부분은 쿼리를 만드는 역할과 쿼리에 필요한 정보를 만드는 역할이 있을 것 같은데요(맞다면 따봉 부탁드려용~! 잘못 이해했다면 다시 말씀주시면 감사하겠습니당.)
역할을 나누면 그 역할에 따라 테스트하기가 더 쉬워질 것 같아용
Table에서는 클래스 정보로 적절한 필드값을 저장했는지, DDLGenerator에서는 쿼리를 잘 만들었는지 확인할 수 있겠네요

2024-02-22 16:37 UTC, jurlring commented
성주님 안녕하세요~!
아래 부분이 걸리지만 낼 출근해야해성 일단 미션 제출합니당~!

1. Column의 책임이 너무 많아요.
    - Id, Column, GeneratedValue 어노테이션 별로 책임과 역할을 나누고 조합할까합니당
2. DB 가 바뀜에 따라 유연한 구조가 아니에요.
    - JPA에서 dialect 값이 어디서 주입되는지? 먼저 확인하고 싶어용

리뷰해주셔서 감사합니당~~~~~ 잘부탁드려용~~~
저도 너드해지고 싶어요!! 찰진 리뷰 부탁드려용~~!

2024-02-23 12:59 UTC, liquidjoo approved these changes
안녕하세요 주리님 
피드백 반영 너무 좋았습니다 👍 
몇 가지 코멘트 남겼는데요~ 다음 단계에 같이 진행해보면 좋을 것 같아요
다음 단계 진행해 주세요 🙇

2024-02-23 12:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/column/ColumnType.java
> +public enum ColumnType {
👍

2024-02-23 12:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/column/GenerationTypeStrategy.java
> +    IDENTITY("AUTO_INCREMENT "),
`IDENTITY` 가 `AUTO_INCREMENT` 가 아닌 경우는 어떻게 할 수 있을까요?
> 데이터베이스의 설정을 가져오는 것이라 :) 이를 해결하려면 어떤 경우를 생각하면 좋을까요~

2024-02-23 12:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/column/MySqlColumn.java
> +    private final ColumnLength length;
피드백 반영 👍

2024-02-23 12:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/column/MySqlColumn.java
> +        boolean hasId = id != null;
id 컬럼 여부를 통해 분기처리가 되는 로직이 존재하는 것 같아요 :)
id 컬럼과 기본 컬럼을 나누어보면 어떨까요?
> 추상화 설계를 해보면 좋습니다

2024-02-23 12:59 UTC, liquidjoo commented on src/main/java/persistence/sql/ddl/table/MySqlTable.java
> +    private final List<MySqlColumn> columns;
일급 컬렉션 활용해보면 좋을 것 같아요 :)
어떤 장점이 있을까요?

2024-02-23 12:59 UTC, liquidjoo commented on src/test/java/persistence/sql/ddl/column/ColumnNameTest.java
> +class ColumnNameTest {
꼼꼼한 테스트코드 좋습니다 👍

2024-02-23 12:59 UTC, merged

2024-02-25 10:06 UTC, jurlring commented on src/main/java/persistence/sql/ddl/column/MySqlColumn.java
> +        boolean hasId = id != null;
앞으로 컬럼마다 @JoinColumn같은 다른 설정값도 추가될텐데, 추상화 설계로 유연한 구조를 가져가면 좋겠네요 :)

2024-02-25 10:10 UTC, jurlring commented on src/main/java/persistence/sql/ddl/table/MySqlTable.java
> +    private final List<MySqlColumn> columns;
일급 컬렉션을 활용하면, 컬렉션을 이용한 비지니스 로직의 책임을 한곳에 둘 수 있다는 장점이 있지용
해당 컬렉션에 비지니스 로직이 많다면 활용하는 것도 좋을 것 같아용