🚀 4단계 - Simple Entity Object
next-step/jpa-query-builder pull request #195
Opened 2024-02-23 15:35 UTC by qwe5507

4단계 리뷰요청드립니다! 

3단계 피드백주신 내용을 수정하는데에 생각보다 애를 먹었습니다! 
- [https://github.com/next-step/jpa-query-builder/pull/172](https://github.com/next-step/jpa-query-builder/pull/172)
- 3단계 피드백 남겨주신 부분에 답글 달았는데 확인 부탁드립니다!

---
4단계를 구현하면서, Class만 사용하는 메소드가 존재하여, QueryBuilder가 일부 수정되었습니다.
- 생성자에 Class타입만 받고, 값이 필요한 메소드에만 object를 추가하게 변경하였습니다.
- DDL QueryBuilder를 커스텀 애노테이션을 사용하고 있었는데, DML과 호환되지 않아 DDL도 DML과 마찬가지로 자카르타 패키지의 애노테이션을 사용하게 변경하였습니다.

2024-02-24 09:09 UTC, wooobo requested changes
안녕하세요 진현님!

4단계 또한 잘 구현해주셨네요! ㅎㅎ
네이밍 부분이랑, 사용하지 않는 클래스에 대한 부분만 봐주시면 바로 `merge`진행하겠습니다!

궁금하신 내용있으시면 DM 주세요~
😄

2024-02-24 09:09 UTC, wooobo commented on README.md
> +### step4 요구사항
>책임을 잘 덜어냈다고 생각이 들지 않아서 찝찝합니다.
검토 한번 해주시며 감사드려요! 

정답은 없잖아요~
만들어가면서 이렇게도 해보고 저렇게도 해보고 고민해보다보면 
점점 좋은 구조가 만들어진다고 생각합니다~

저는 충분히 잘 하셨다고 생각합니다~ 👍

2024-02-24 09:09 UTC, wooobo commented on src/main/java/persistence/sql/entity/EntityManager.java
> +public interface EntityManager {
👍

2024-02-24 09:59 UTC, qwe5507 commented on src/main/java/persistence/sql/dml/EntityValue.java
> +public class EntityValue {
다른 일이 많아 정신없이 새벽에 하다보니, 삭제하는 걸 깜빡했네요. 부끄럽습니다

2024-02-24 11:31 UTC, qwe5507 commented
이번 주차 오프라인 교육을 받고, Dialect를 활용한 추상화를 힌트를 얻어 앞으로 계속 사용 할 QueryBuilder이기 떄문에 
피드백 외에 QueryBuilder의 리팩토링을 진행 하고 리뷰 재요청 드립니다!
KeyGenerator, H2KeyGenerator보다, DB별로 다르게 적용할 수 있는 부분을 DIract 인터페이스에 추상화 하고, 구현체에 구현하였습니다.
다음단계 진행하면서도 지속적으로 리팩토링 하겠지만, 태화님이 봐주셨으면 해서 같이 리뷰 요청드립니다!

2024-02-25 04:33 UTC, wooobo approved these changes
안녕하세요 진현님!

4단계까지 잘 진행해주셨습니다.
그럼 이만 `merge`진행하겠습니다.

남은 미션 즐겁게 완주하시기를 응원하겠습니다!
그럼 즐거운 주말 되세요~

2024-02-25 04:33 UTC, wooobo commented on src/main/java/persistence/sql/dialect/H2Dialect.java
> +public class H2Dialect extends Dialect {
이거 좋네요! ㅎ

```
- dialect
  - h2
    - H2Dialect.java
```

이런 패키지 구조도 좋을것 같네요~

2024-02-25 04:33 UTC, wooobo commented on src/main/java/persistence/sql/dialect/JavaClassCodeTypeMappings.java
> +public class JavaClassCodeTypeMappings {
2주차 강의때 해당 내용이 나올꺼라서 말을 아끼고 있었는데, 
새로운 패턴을 찾으셨군요!  👍

2024-02-25 04:33 UTC, wooobo commented on src/main/java/persistence/sql/dialect/JavaClassCodeTypeMappings.java
> +    private static final ConcurrentHashMap<Class, Integer> javaClassToCodeTypeMap = new ConcurrentHashMap();
```suggestion
    private static final ConcurrentHashMap<Class<?>, Integer> javaClassToCodeTypeMap = new ConcurrentHashMap<>();
```

ㅎㅎ

2024-02-25 04:33 UTC, wooobo commented on src/test/java/persistence/sql/dml/QueryBuilderTest.java
> +        QueryBuilder queryBuilder = new QueryBuilder(person.getClass(), new H2Dialect());
👍

2024-02-25 04:33 UTC, wooobo commented on src/main/java/persistence/sql/dml/QueryBuilder.java
>          return String.format("delete from %s where %s = %s", this.entityTableMeta.name(),
뭔가 Dialect 냄새가 나는군요 😄 
```suggestion
        return String.format(dialect.blabla, this.entityTableMeta.name(),
```

2024-02-25 04:33 UTC, merged

2024-02-25 04:48 UTC, qwe5507 commented on src/main/java/persistence/sql/dialect/H2Dialect.java
> +public class H2Dialect extends Dialect {
좋네요 ㅎㅎ 다음단계에 수정해서 진행하겠습니다