🚀 4단계 - Simple Entity Object
next-step/jpa-query-builder pull request #202
Opened 2024-02-24 10:52 UTC by djawnstj

2024-02-24 12:25 UTC, jwee0330 requested changes
안녕하세요 준서님
4단계 미션도 잘 구현해 주셨네요 :)
몇가지 코멘트 드렸는데 한번 생각해 보시고 의견 남겨주시면 좋을것 같아요🙂
그 이후에 구조개선을 해볼지 다음 단계에서 구조개선을 진행할지 이야기 나누어보면 좋을것 같습니다 :) 피드백 반영후 다시 PR 요청 부탁드립니다 🙇🏻‍♂️

2024-02-24 12:25 UTC, jwee0330 commented on src/main/java/persistence/sql/mapping/ColumnBinder.java
> +        return new Column(columnName, sqlType, new Value(field.getType(), sqlType), length, nullable, unique);
이미 Column class 내부에 length, nullable, unique 의 기본값이 설정되어 있네요
기본값 활용할 수 있도록 Column 생성자 추가하는건 어떻게 생각하세요?
```suggestion
        final jakarta.persistence.Column columnAnnotation = field.getAnnotation(jakarta.persistence.Column.class);
        if (columnAnnotation != null) {
            return new Column(columnName, sqlType, new Value(field.getType(), sqlType), length, nullable, unique);
        }
        return new Column(columnName, sqlType, new Value(field.getType(), sqlType));
```

2024-02-24 12:25 UTC, jwee0330 commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +    private final ColumnBinder columnBinder;
ColumnBinder 는 TableBinder 외에서 사용되는 곳이 없는것 같은데요,
TableBinder 내부에서만 사용되어도 좋을것 같네요 🙂

2024-02-24 12:25 UTC, jwee0330 commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +        final Table table = tableBinder.createTable(clazz, columnBinder.createColumns(clazz));
insert 쿼리와 반대로 select/ remove 쿼리의 경우는 id 값을 제외하고 항상 동일할 것 같은데요,
지금 구조는 find 메소드가 호출될 때마다 Table 객체를 생성하고 있는데요
성능상 더 개선할 수 있는 방법이 있을까요?

2024-02-24 13:02 UTC, djawnstj commented on src/main/java/persistence/sql/mapping/ColumnBinder.java
> +        return new Column(columnName, sqlType, new Value(field.getType(), sqlType), length, nullable, unique);
생성자를 나눠서 필요에 따라 호출하는게 훨씬 좋은 코드 같네요.
피드백 감사합니다!

2024-02-24 13:04 UTC, djawnstj commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +    private final ColumnBinder columnBinder;
TableBinder 내부에 ColumnBinder 를 선언하는 구조로 수정해보겠습니다🙂

2024-02-24 13:04 UTC, djawnstj commented on src/test/java/persistence/entity/SimpleEntityManagerTest.java
> +}
인텔리제이 단축키로 테스트 클래스를 생성하니 개행문자가 빠지네요ㅠㅠ
설정을 추가해야겠습니다.
감사합니다!

2024-02-25 02:56 UTC, jwee0330 commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +        final Table table = tableBinder.createTable(clazz, columnBinder.createColumns(clazz));
Table 이라는 메타정보를 담은 객체가 존재하는건 좋은 구조인것 같아요.
제가 피드백 드린 내용은 질문주신 class 로부터 리플랙션을 이용하여 쿼리를 생성하는 부분일 선택할지 테이블 객체를 생성하여 활용할지의 선택에 대한 피드백을 드린건 아니었어요ㅎ

두 방법 모두 find() 호출 시점에 reflection 으로 쿼리를 생성하고, table 객체를 생성하여 쿼리를 생성하는 부분은 동일 할 것 같네요.
제가 드린 피드백은 클래스 정보는 컴파일 시점에 알수있는 정적 정보들이고, 해당 쿼리도 미리 만들어 놓을 수 있지 않을까? 라는 생각에서 드린 피드백이었습니다 :) 이런 부분도 한번 깊게 고민해 보시면 훨씬 얻어가시는게 많을 것 같아요 🙏🏻

2024-02-25 03:02 UTC, jwee0330 approved these changes
안녕하세요 준서님 :)
피드백 반영 하시느라 정말 고생 많으셨어요.
제가 드린 피드백에 질문 주신 부분에 대해서는 코멘트 남겨놓았으니 한번 읽어보시고 천천히 고민해 보시면 좋을것 같습니다 🙂 다음단계로 넘어가서도 고민해 보시면 좋을것 같아요.
고민하시는만큼 많은걸 얻어가셨으면 좋겠습니다 🙂
2주차 미션도 파이팅하세요 💪

2024-02-25 03:02 UTC, merged