🚀 4단계 - Simple Entity Object
next-step/jpa-query-builder pull request #210
Opened 2024-02-26 14:44 UTC by shinseongsu

안녕하세요 리뷰어님~
step3에서 비슷한 기능을만들어놔서 재사용하는 식으로 만들었습니다.

이번에는 rebase 확실히 진행하였습니다 😄 

# 요구사항

## 4단계 요구사항

- [x] EntityManager find 구현
- [x] EntityManager persist (insert) 구현
- [x] EntityMaanger remove (delete) 구현

2024-02-26 18:11 UTC, jongmin4943 requested changes
안녕하세요! 성수님
4단계 미션 잘 진행해주셨네요 💯

이미 이전 단계에서 잘 만들어 놓으셔서 4단계는 피드백 드릴게 많이 없네요 😃
몇가지 코멘트 남겼는데 확인하고 다시 요청 주세요 🙇

궁금한 사항은 언제든 추가 코멘트 또는 DM 주세요! 😃

2024-02-26 18:11 UTC, jongmin4943 commented on src/main/java/persistence/sql/entity/manager/EntityManagerImpl.java
> +import persistence.sql.dml.repository.RepositoryMapper;
`EntityManagerImpl` 에서 `RepositoryMapper` 를 참조하고 있어서 패키지 순환참조가 일어나고 있는것 같아요 🤔
`Repository` 는 `EntityManager` 을 알고 있어도 되지만 `EntityManager` 는 `Repository` 의 존재를 몰라야 하지 않을까요? 😃

2024-02-26 22:56 UTC, shinseongsu commented on src/main/java/persistence/sql/dml/repository/RepositoryImpl.java
>      }
예외가 날수 있는구간이군요 예외넣도록 하겠습니다~

2024-02-26 22:57 UTC, shinseongsu commented on src/main/java/persistence/sql/entity/manager/EntityManagerImpl.java
> +        final EntityManagerMapper<T> entityManagerMapper = new EntityManagerMapper<T>(entity, entity.getClass(), pkDomainType.getName());
좋은 의견 감사합니다~
확실히 뒤쪽 제네릭이빠지니 깔끔한 느낌이 드네요

2024-02-26 22:58 UTC, shinseongsu commented on src/main/java/persistence/sql/entity/model/Criteria.java
> +    }
비슷한 패키지가 없어서 model에 넣었는데 조건 관련한 패키지를 만들어 나눠서 써야겠네요 👍

2024-02-26 22:59 UTC, shinseongsu commented on src/main/java/persistence/sql/dml/repository/RepositoryImpl.java
> +public class RepositoryImpl<T, K> implements Repository<T, K> {
repository도 entityManager를 만드는줄 모르고 만들었는데 ㅠㅠ 사용자가 쓸수 있도록 편한 위치에 넣도록 하겠습니다

2024-02-26 23:00 UTC, shinseongsu commented on src/main/java/persistence/sql/entity/model/Criterias.java
> +    }
아하 그렇군요
구글 번역기를 써서 만들다 보니, 직역으로 해석된 단어를 썼는데 알려주셔서 감사합니다~

2024-02-26 23:01 UTC, shinseongsu commented on src/main/java/persistence/sql/entity/manager/EntityManagerImpl.java
> +import persistence.sql.dml.repository.RepositoryMapper;
repository가 원래 entitymanger만들지 전에 영역이 였는데, entityamnagermapper로 이름 바꾸고 패키지도 바꿔서 써도 될것같아요
좋은 피드백 주셔서 감사합니다 😄

2024-02-27 01:15 UTC, shinseongsu commented
# 수정사항
- delete 시, 예외처리 추가
- Repository 패키지 수정
- jdbcTempalte Mapper 역할을 EntityManager로 위임
- model에 있던 Where 객체 위치 수정

2024-02-27 03:31 UTC, jongmin4943 commented on src/main/java/persistence/repository/RepositoryImpl.java
> +public class RepositoryImpl<T, K> implements Repository<T, K> {
피드백 반영 👍

2024-02-27 03:33 UTC, jongmin4943 commented on src/main/java/persistence/repository/RepositoryImpl.java
> +    }
이제 Null 에 안전해지겠네요 💯 
사소하지만 위의 `findById` 처럼 Optional 을 이용 해보는 것도 좋을 것 같아요 😃

2024-02-27 03:34 UTC, jongmin4943 commented on src/main/java/persistence/sql/entity/conditional/Criteria.java
> +public class Criteria {
사소하지만 개인적으로 Criteria 는 쿼리성격이 강해서 dml 의 query 패키지 밑으로 가는것도 좋아 보여요 😃

2024-02-27 03:37 UTC, merged

2024-02-27 07:38 UTC, shinseongsu commented on src/main/java/persistence/sql/entity/conditional/Criteria.java
> +public class Criteria {
그렇군요 생각해보니 ddl 에서 사용할 일이 없겠군요 ㅎㅎ
마지막까지 좋은 리뷰 감사합니다