Step4 - Simple Entity Object
next-step/jpa-query-builder pull request #215
Opened 2024-02-28 14:18 UTC by who-is-hu

이전 피드백도 반영했습니다.
잘부탁드립니다!

2024-02-28 16:40 UTC, jongmin4943 requested changes
안녕하세요 용후님!

4단계 미션 잘 진행 해주셨네요 💯 
사소한 코멘트 몇가지 남으니 해당 부분 확인 해주세요 🙇

요구사항은 다 만족 했으나 TODO 로 남겨두신 부분이 있어 현재단계에서 진행 하시려면 반영해주시고, 
다음 단계로 넘어가셔서 진행하실 계획이시라면 말씀 주세요! 그럼 피드백 부분 반영만 확인하고 바로 merge 를 진행하겠습니다 🚀  

궁금한 사항은 언제든 추가 코멘트 또는 DM 주세요! 😃

2024-02-28 16:40 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityMangerImpl.java
> +    private H2Dialect dialect;
```suggestion
public class EntityMangerImpl implements EntityManger {
    private final JdbcTemplate jdbcTemplate;
    private final H2Dialect dialect;
```
필드를 불변(final) 로 가져간다면 어떤 이점이 있을까요? 😃

2024-02-28 16:40 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityMangerImpl.java
> +    }
persist 시 id 에 대해 고민하고 구현해주셨네요! 👍 

두가지 부분에서 궁금한점이 있어요!

리플렉션으로 id 를 가져오셨는데 만드신 `ColumnData` 를 사용 하지 않으신 이유가 있으실까요? 👀 

`rs.getLong(1)` 과 `id - 1` 같은 하드코딩 된 부분은 상수나 메서드로 표현해서 가독성을 높이는게 좋을 것 같아요
다만, dialect 로 `generatedIdQuery` 를 이용해 id 를 가져오는 구조로 만들어 주셨는데, getLong(1) 이나 1을 빼는 로직이 다른 db 에도 똑같이 적용이 된다고 보장할 수 있을까요? 🤔

id 를 가져오는 부분은 이번 query builder 미션의 목표가 아니니 두번째 피드백은 반드시 반영해주지 않으셔도 됩니다 😃

2024-02-28 16:40 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/SelectQueryBuilder.java
> +        names.add(columns.getKeyColumn().getName());
피드백 반영 감사합니다 👍👍 
객체에게 직접 `key 컬럼 이름 줘` 라고 물어보시는건 어떨까요? 😃

![image](https://github.com/next-step/jpa-query-builder/assets/77711322/56be4bb3-eccf-4ef6-a7ef-7fb5a69c3706)

2024-02-28 16:40 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/WhereBuilder.java
>      }
책임의 분리가 잘 된것 같아요 💯

2024-02-28 16:40 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityMangerImplTest.java
> +    private InsertQueryBuilder insertQueryBuilder = new InsertQueryBuilder(Person.class);;
사소하지만 개인적으로 static 이 위로, 멤버필드는 아래로 오는 구조가 눈에 잘 들어오더라구요 😃

2024-02-29 13:28 UTC, who-is-hu commented on src/main/java/persistence/entity/EntityMangerImpl.java
> +    private H2Dialect dialect;
좀 찾아봤는데 GC 성능에 대한 내용도 덕분에 읽어보게 됐네요 감사합니다~

2024-02-29 13:49 UTC, who-is-hu commented
제네릭 부분은 다음단계에서 진행해 보도록하겠습니다!

2024-02-29 14:05 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityMangerImplTest.java
> +    EntityManger entityManger = new EntityMangerImpl(jdbcTemplate, new H2Dialect());
피드백 반영해주셨네요 👍 
사소하지만 다른 필드들과 마찬가지로 `EntityManager` 도 접근제어자를 넣어서 통일시켜주는것도 좋을것같아요 😃

2024-02-29 14:05 UTC, jongmin4943 commented on src/main/java/persistence/entity/H2GetGeneratedIdStrategy.java
> +}
id 가져오는 부분을 추상화 시켜주셨네요 👍  
이름에 Get 이 들어가는데 클래스 이름에 행위가 들어가는게 어색하게 느껴지네요 😅

2024-02-29 14:05 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityMangerImpl.java
> +    }
> ColumnData 가 entity의 값을 조작하는게 어색한것같아서 entityManger에 따로 구현했어요.

고민해주시고 나온 결론이라면 ok 입니다!
개인적으로 entity 의 값을 직접 조작하진 않더라도, entity 의 정보이기 때문에 이미 가지고 있던 id 필드를 조회하는곳에 사용해도 괜찮다 생각해요 😄

2024-02-29 14:07 UTC, jongmin4943 approved these changes
안녕하세요! 용후님

미션 4단계까지 오면서 너무 많은 피드백을 드린 것 아닌가 걱정했는데
끝까지 잘 반영해주셔서 너무 감사합니다 👍 

1주차 쿼리빌더 미션 하시느라 정말 고생 많으셨습니다. 🙇
다음 미션도 화이팅 입니다! 🚀

2024-02-29 14:08 UTC, merged

2024-02-29 14:09 UTC, who-is-hu commented on src/test/java/persistence/entity/EntityMangerImplTest.java
> +    EntityManger entityManger = new EntityMangerImpl(jdbcTemplate, new H2Dialect());
아이고 계속 실수하네요 죄송합니다ㅠ

2024-02-29 14:16 UTC, who-is-hu commented on src/main/java/persistence/entity/H2GetGeneratedIdStrategy.java
> +}
좀더 고민해보고 바꿔볼게요

2024-02-29 14:27 UTC, who-is-hu commented
리뷰 봐주시느라 너무 고생하셨습니다. 많이 배웠습니다.
마지막으로 궁금한것이

> 개인적으로 entity 의 값을 직접 조작하진 않더라도, entity 의 정보이기 때문에 이미 가지고 있던 id 필드를 조회하는곳에 사용해도 괜찮다 생각해요 😄
이부분에 ColumnData에 Field도 저장해두고 그걸 쓰는 방식을 말씀하신건가요?
그렇다면 값조작도 안하고 리플렉션도 몰수있어서 좋은것같아요

2024-02-29 14:35 UTC, jongmin4943 commented
> 이부분에 ColumnData에 Field도 저장해두고 그걸 쓰는 방식을 말씀하신건가요? 그렇다면 값조작도 안하고 리플렉션도 몰수있어서 좋은것같아요

개인적인 관점이니 참고만 부탁드려요 🙏 
`ColumnData` 는 entity 의 정보를 책임지는 클래스이다보니 저라면 `ColumnData` 에 값을 바인딩하기보단, 값을 추출하거나 바인딩할때 해당 객체를 이용해볼것 같아요! 어떤방식으로 이용할지는 전적으로 만드는 사람의 자유라고 생각하구요 ㅎㅎ

`setIdToEntity` 에서 하고 있는 리플렉션인 아이디 가져오는부분은 `EntityManager` 가 알아야하는 책임일지 고민해보셔도 좋을것 같아요. `EntityManager` 의 역할을 고민해보는거죠 ㅎㅎ 👍

2024-02-29 14:39 UTC, who-is-hu commented
아 이해했습니다 굳이 바인딩까지 할필요는 없고 로직만 옮겨둘수도 있겠네요. 감사합니다~