2단계 QueryBuilder DDL 구현
next-step/jpa-query-builder pull request #250
Opened 2024-10-12 07:53 UTC by jshans40

안녕하세요 기륭님! 아직 많이 부족한거 같은데 이번 코드 리뷰도 잘 부탁드립니다!🙏

이번 과제 진행하면서 고민이 되었던 부분에 대해서 남깁니다~ 

[？고민  되었던 부분😳]
- 역할 & 책임을 나누기 위해서 Column, Table 관련해서 일부 객체로 나누었는데 Column 객체 분리시 해당 객체가 너무 커진것 같다는 느낌이 들었습니다.  이정도로 충분할지? 더 나눠야할지? 아니면 미션 요구사항에 더 집중해야할지 고민이 많이 되었습니다.
- 요구사항 4번을 보면 "@Entity, @Table를 고려해서 잘 작성해보자" 가 있는데 테이블 생성에서도 Entity에노테이션이 있어야만 동작하게 하는것이 맞지 않을까.

감사합니다!! 😄

2024-10-12 08:37 UTC, NamKey commented
현재 리뷰 진행하고 있는데 질문주신 부분에 있어서 먼저 답변드립니다!

1. 역할 & 책임을 나누기 위해서 Column, Table 관련해서 일부 객체로 나누었는데 Column 객체 분리시 해당 객체가 너무 커진것 같다는 느낌이 들었습니다. 이정도로 충분할지? 더 나눠야할지? 아니면 미션 요구사항에 더 집중해야할지 고민이 많이 되었습니다.

- 처음부터 클래스의 역할과 책임을 작게 세분화한다면 과도한 추상화가 될 수도 있고 크게 한다면 반대로 확장과 유연성이 떨어지는 부분에 대해서 적정선을 질문주신 거 같은데, 적정선이라 함은 요구사항에 따라 도메인에 따라 많이 견해가 다를수도 있고 주관적인 부분이라서 상혁님이 생각하시는 적당한 크기로 작성해주시면 됩니다!
- 부연설명드리면 왜 해당 메서드나 필드가 Column 클래스에 속해져 있어야만 하는가에 대한 답변이 떠오르신다면 현재의 요구사항에서는 상혁님이 설계하신 크기가 적절하게 설계되었다고 생각합니다.

2. 요구사항 4번을 보면 "entity, table를 고려해서 잘 작성해보자" 가 있는데 테이블 생성에서도 Entity에노테이션이 있어야만 동작하게 하는것이 맞지 않을까.

- 사용하시는 실제 JPA는 어떤가요? 비교해보시면서 필요하다면 넣어보시는 것도 좋고, 이미 있다면 이런 이유로 넣었겠구나라고 이해하시면 될거 같아요!

2024-10-12 09:07 UTC, NamKey requested changes
안녕하세요 상혁님! 😄

빠르게 2번째 미션 진행해주셨네요! 고생많으셨습니다 💪
단위 테스트 코드도 잘 작성해주셨습니다.
다만, 생각해볼 포인트를 코멘트로 남겼는데 답변과 피드백 반영 부탁드리겠습니다 🙇‍♂️

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +        return Optional.ofNullable(ddlColumnNullableString.get(nullable)).get();
Optional에 다시 넣은뒤에 get()을 바로 호출하는 이유가 있으실까요?
만약에 Optional 안에 null 이 들어가있다면 get()을 했을 때 어떤 예외가 발생할지 예상하실 수 있으실까요?

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +            throw new NullPointerException("Generation Type이 존재하지 않습니다.");
NullPointerException이 사용되었는데, 해당 부분은 요구사항에 대한 검증 영역이라고도 생각합니다!
NullPointerException이 적절할지 생각해보셨으면 좋겠습니다!

<details>
    <summary>Hint</summary>

<!-- summary 아래 한칸 공백 두고 내용 삽입 -->
Null 에 대한 처리를 못해 발생한 NPE와 요구사항에 맞지 않아 발생한 NPE를 어떻게 구분할 수 있을까요?

</details>

2024-10-12 09:07 UTC, NamKey commented on src/test/java/persistence/sql/ddl/model/DDLColumnsTest.java
> +            assertThatThrownBy(() -> new DDLColumn(null))
꼼꼼하게 Message까지 검증해주셨네요! 💯
작성할때는 손이 더 가더라도 나중에 동료개발자나 다른 분들이 볼 경우에는 도움이 많이 되어 좋습니다!

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/model/TableName.java
> +            throw new NullPointerException("클래스가 존재하지 않습니다.");
TableName 객체를 생성할 때와 getTableName에서 모두 clazz에 대해 Null 체크를 하신 이유가 있을까요?

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +        return String.join(",", this.fields.stream().map(this::makeColumnDDL).toList());
_JPA의 모든 미션들은 Java 11을 기준으로 작성해주시면 감사하겠습니다!_
- 이번부터 Java21  까지 + Kotlin 사용가능한 것으로 변경되었다고 하네요! 편하신 환경에서 작업진행주시면 됩니다!

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/H2DropQueryBuilder.java
> +            throw new IllegalArgumentException("class가 존재하지 않습니다.");
많은 곳에서 같은 메세지가 반복되는데, 이런 예외들을 하나로 공통화하는 건 어떠실까요?

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/H2DropQueryBuilder.java
> +    private static final String SPACE = " ";
반복적으로 사용되는 경우 static 변수로 분리해주셨네요 👍
이런 부분 하나하나가 디테일이죠 😁

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +        if (field.isAnnotationPresent(Id.class)) {
2번에 질문주셨던 부분과 연결시켜 생각하면, `@Id와 `@GeneratedValue 는 따로 사용해도 될까요?

2024-10-12 09:07 UTC, NamKey commented on src/main/java/persistence/Application.java
> +            CreateQueryBuilder createQueryBuilder = new H2CreateQueryBuilder(Person.class);
데이터베이스가 달라지면 DDL에 대한 문법이 달라질텐데, 모든 문법이 달라질지 공통적인 부분이 있을지 생각해보시고 더 추상화해보셔도 좋을거 같아요!

<details>
    <summary>Hint</summary>

<!-- summary 아래 한칸 공백 두고 내용 삽입 -->
데이터베이스가 달라지면 어떤 부분이 달라질까요? SQL은 이미 ANSI-SQL로 표준화되어 있고 지원하는 기능에 따라 추가되는 문법이 있긴하지만 많은 부분이 호환되도록 설계되어있습니다!

</details>

2024-10-12 09:07 UTC, NamKey commented on src/test/java/persistence/sql/ddl/H2CreateQueryBuilderTest.java
> +class H2CreateQueryBuilderTest {
현재 단위테스트만 있는데 통합테스트가 있다면 더 견고한 구조가 될 거 같습니다! 💪

2024-10-13 09:09 UTC, jshans40 commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +        return Optional.ofNullable(ddlColumnNullableString.get(nullable)).get();
이 부분은 제가 놓쳤네요 
Optioanl에 대한 값이 없을 경우 NullPointException이 발생할것으로 예상됩니다.
따로 검증 부분 추가가 필요할 것 같습니다!

2024-10-13 09:12 UTC, jshans40 commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +            throw new NullPointerException("Generation Type이 존재하지 않습니다.");
처음에 NullPointException으로 모두 처리했다가 IllegalArgumentException으로 변경했는데 이부분이 변경이 안되었네요 ㅠㅠ
NullPointerException 보단 요구사항 검증이기 떄문에 IllegalArgumentException가 더 적절해보입니다!

2024-10-13 09:13 UTC, jshans40 commented on src/main/java/persistence/sql/ddl/model/TableName.java
> +            throw new NullPointerException("클래스가 존재하지 않습니다.");
객체를 생성했을때 class에 대한 유효성 검사가 되었으므로 해당 메소드에서는 따로 유효성 검사를 할 필요가 없어보입니다.
수정하겠습니다!

2024-10-13 09:27 UTC, jshans40 commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +        if (field.isAnnotationPresent(Id.class)) {
@Id의 경우에는 @GeneratedValue 없이 사용할 수 있지만,
반대로 @GeneratedValue 는 @Id없이 사용할 수 없습니다.
@GeneratedValue에 존재 유무를 확인할 때 @Id에 대한 존재유무도 같이 확인해야할 것 같습니다!

2024-10-13 13:28 UTC, NamKey approved these changes
안녕하세요 상혁님!
빠른 피드백 반영과 더불어 잘 작성해주셨습니다 💯

피드백 반영된 부분도 요청주셔야지 제가 바로 확인할 수 있어서 
다음에는 리뷰요청 다시 주시면 감사하겠습니다! 🙇‍♂️
앞으로 진행할 부분에 있어서 한번 생각해보셨으면 하는 부분이 있어서 코멘트 남겨놓았는데 확인부탁드립니다! 
다음 미션에서 함께 생각하시면 더 좋을거 같아서 이번 미션은 여기서 마무리하도록 하겠습니다 😁

2024-10-13 13:28 UTC, NamKey commented on src/main/java/persistence/sql/ddl/ExceptionUtil.java
> +public class ExceptionUtil {
Util 로써 만들어주셨네요!
상혁님은 static class/method에 대해서 어떻게 생각하시나요?

2024-10-13 13:28 UTC, NamKey commented on src/main/java/persistence/sql/ddl/model/DDLColumn.java
> +        if (field.isAnnotationPresent(Id.class) && field.isAnnotationPresent(GeneratedValue.class)) {
답변주신 부분 반영해주셨네요 👍

2024-10-13 13:28 UTC, NamKey commented on src/main/java/persistence/sql/ddl/AbstractCreateQueryBuilder.java
> +public abstract class AbstractCreateQueryBuilder implements CreateQueryBuilder {
1/ 추상클래스로 만들어주셨는데, 인터페이스와 어떤 차이가 있는지 알고 계신가요?
2/ 어떤 차이가 있는지 알고 계신다면 추상클래스를 사용하신 이유가 있으실까요?
3/ 상속(Heritance)과 조합(Composition) 중에 어떤 방식을 선호하시나요?

2024-10-13 13:28 UTC, merged