Step2 : QueryBuilder DDL
next-step/jpa-query-builder pull request #257
Opened 2024-10-12 13:21 UTC by jdalma

안녕하세요 이번 리뷰도 잘 부탁드립니다 ㅎㅎ

1단계에서 말씀해주신 부분도 반영해보았습니다~

2024-10-12 15:15 UTC, jongmin4943 requested changes
안녕하세요 현준님!

2단계 미션 잘 진행해주셨네요 💯 
몇 가지 생각해볼만한 코멘트들 남겼는데 확인 후 재 요청 부탁드려요 🙇

궁금하시거나 고민 되시는 부분이 있으시다면 언제든 코멘트나 DM 주세요! 🔥

2024-10-12 15:15 UTC, jongmin4943 commented on README.md
> +2. `@Id` 어노테이션이 여러 개라면 복합키를 생성
엣지 케이스에 대한 고민을 해보셨군요 👍 

좋은 고민들이지만, 현재 미션에서는 요구되지 않는 부분들이니 지금은 너무 고민 안하셨으면 좋겠습니다 :)

2024-10-12 15:15 UTC, jongmin4943 commented on src/main/java/entity/Person.kt
> +class Person (
```suggestion
@Table(name = "users")
@Entity
class Person (
```

요구사항 3 에 추가 된  `@Table(name = "users")` 부분도 추가 되어야 하는데 누락된 것 같아요 😅

2024-10-12 15:15 UTC, jongmin4943 commented on src/main/java/exception/ColumnTypeUnavailableException.kt
> +class ColumnTypeUnavailableException(msg: String): RuntimeException(msg)
커스텀 예외 선언 👍

2024-10-12 15:15 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/Column.kt
> +data class Column (
현재 `Column` 은 클래스 필드의 정보 추출, 검증, 쿼리 생성 등 많은 책임을 가지고 있는 것 같아요. 🤔

쿼리를 생성하는 로직과 필드 정보를 추출하는 책임을 나누면 좋을 것 같다고 생각하는데 어떻게 생각하시나요? 😃

2024-10-12 15:15 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/Column.kt
> +        if (isTransientField()) return ""
사소하지만, 개인적으로 if문에 코드블럭을 명시해줘야 한다고 생각해요.

- if 문이 보이면 코드블럭을 예상하는데 1줄짜리인 경우, 코드블럭이 없어서 예상과 다른 부분으로 인해 가독성을 해친다고 느껴요.
- if 문은 코드블럭을 가진다. 라는 일관성을 지키는게 실수를 줄여준다고 생각해요.
- if 문 내부에 로직이 늘어나는 경우 블럭을 그때 추가하는 것 보단 미리 만들어 놓는게 나중에 코드리뷰를 해주는 사람 입장에서나 코드를 고치는 사람 입장에서 편하다고 생각해요.

현준님은 어떻게 생각하시나요?

2024-10-12 15:15 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/Column.kt
> +        }
만들면서 배우는 JPA 미션 진행하면서 [객체지향생활체조](https://edu.nextstep.camp/s/BkhC9zSg/ls/ifdcwNoy)를 지켜보시는걸 권장 드려요 :)

![image](https://github.com/user-attachments/assets/2854839f-63ae-4307-992f-3053f4e913c6)

2024-10-12 15:15 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/Column.kt
> +        }
DB 마다 columnType 을 나타내는 방법이 달라지는 경우 분기가 많이 늘어날 수 있을 것 같아요 🤔
또한, VARCHER 의 length 도 `@Column` 의 속성으로 설정이 가능하기에 255로 고정할 수 없을 것 같아요 😢

이런 부분은 어떤식으로 해결할 수 있을까요?

2024-10-12 15:15 UTC, jongmin4943 commented on src/test/java/persistence/ApplicationTest.kt
> +    }
H2 를 이용한 통합테스트를 만들어주셨네요. 훌륭합니다 💯💯

2024-10-12 15:15 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/ColumnTest.kt
> +        }
꼼꼼한 예외 테스트 👍

2024-10-12 15:15 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/TableManagerTest.kt
> +        }
개인적으로 `TableManager` 라는 이름을 가진 클래스에게 `@Entity`가 없는 클래스가 전달된다면 예외를 발생시키는게 좋지 않나? 라는 생각이 들어요.

`TableManager` 를 사용하는 사람 입장에서는 클래스를 넘겼는데, 아무 반응도 하지 않는다면 내부 구현을 보지 않는 이상 그 이유를 알 수 없기에 명시적으로 알려주는게 좋다고 생각이 드는데 어떻게 생각하시나요? 😃

2024-10-12 15:15 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/TableTest.kt
> +        }
개인적으로 테스트케이스가 조금 부족하다고 느껴져요. 😢

구현 내부적으로 분기가 있는 부분들에 대한 테스트 케이스가 안보이는데, 
요구사항 1 일때 나오는 쿼리, 요구사항 2일때 나오는 쿼리, 요구사항 3 일때 나오는 쿼리가 조금씩 다 달라지는 부분에 대한 케이스들도 추가해주시면 감사하겠습니다 😃

2024-10-12 15:15 UTC, jongmin4943 commented on src/test/java/study/ReflectionTest.kt
> +        }
피드백 반영해주셨군요! 감사합니다 😃

2024-10-14 04:49 UTC, jdalma commented on src/main/java/persistence/sql/ddl/Column.kt
> +        if (isTransientField()) return ""
말씀하신 일관성에 대해 생각하게 되네요 ㅎㅎ 일관성을 지켜서 코드를 읽는 비용을 최대한 아끼는것이 좋겠습니다
감사합니다!

2024-10-14 05:42 UTC, jdalma commented on src/test/java/persistence/sql/ddl/TableManagerTest.kt
> +        }
저도 고민했던 부분인데 클라이언트 입장에서 생각해보지 않았었네요 ㅎㅎ 초기화 시점에서 예외를 던지지 않고 그냥 흘러버리면 사용하는 시점에서 예외가 발생할 것 같네요
말씀하신대로 TableManager가 예외를 던지는 것이 맞을 것 같습니다! 감사합니다 ㅎㅎ

2024-10-14 08:41 UTC, jdalma commented
> DB 마다 columnType 을 나타내는 방법이 달라지는 경우 분기가 많이 늘어날 수 있을 것 같아요 🤔 또한, VARCHER 의 length 도 `@Column` 의 속성으로 설정이 가능하기에 255로 고정할 수 없을 것 같아요 😢
> 
> 이런 부분은 어떤식으로 해결할 수 있을까요?

말씀하신대로 DB 종류에 따라 컬럼 타입을 구분해야 한다면 자바가 DB의 커넥션을 얻는 로직을 추상화하기 위해 [`DataSource`](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.sql/share/classes/javax/sql/DataSource.java) 인터페이스를 도입한 것과 같이 추상화를 통해 런타임에 구현체를 꽂아줘야할 것 같습니다.

혹시 말씀하신 DB 종류와 컬럼 사이즈 구별도 이번 단계에서 진행하면 될까요??
일단 parse 패키지를 추가하면서 파싱에 대한 로직을 일반화한 부분까지 리뷰 요청드리겠습니다 ㅎㅎ

2024-10-14 12:21 UTC, jongmin4943 requested changes
안녕하세요 현준님!

피드백 반영 해주신 것 확인했습니다. 👍  다만, 제가 드렸던 피드백 방향과 조금 다르고, 다음 단계 전에 구조를 잡고 가면 좋을 것 같아 한번 더 RC 드려요. 확인 후 재요청 부탁드릴게요 🙇

궁금하시거나 고민 되시는 부분이 있으시다면 언제든 코멘트나 DM 주세요! 🔥

2024-10-14 12:21 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/DefinitionQueryManager.kt
> +    }
피드백 반영 👍

2024-10-14 12:21 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/column/Column.kt
> +) {
제가 피드백 드렸던 방향하고는 조금 다른 모양으로 나왔네요. 😅

> 현재 Column 은 클래스 필드의 정보 추출, 검증, 쿼리 생성 등 많은 책임을 가지고 있는 것 같아요. 🤔
>쿼리를 생성하는 로직과 필드 정보를 추출하는 책임을 나누면 좋을 것 같다고 생각하는데 어떻게 생각하시나요? 😃

`Column` 여전히 클래스 정보 추출을 위해 `field`를 멤버로 가지고 있고, `createQuery` 메서드 까지 제공하여 쿼리 생성의 책임도 지고 있어요. `Column` 을 사용하고 있는 주체인 `DefinitionQueryManager` 도 쿼리를 만드는 일과 클래스 정보를 추출 및 검증하고 있죠.

저는 쿼리 생성 로직과 클래스 정보를 추출하는 책임을 나눈다면 구조가 조금 더 유연해진다고 생각해요. 😃

예를 들어, 클래스 정보를 리플렉션 대신 파일에서 읽거나 외부에서 주입받는 방식으로 변경된다고 하면, 리플렉션에 의존한 모든 클래스들을 일일이 찾아서 수정해야 하는 문제가 발생할 수 있어요.

또는, DB 마다 달라지는 쿼리들을 위한 변경이 클래스 정보를 추출, 검증하는 부분을 오염 시킬 가능성도 생길 수 있죠.

클래스 정보를 추출해 필요한 정보를 제공하는 책임과, 이를 바탕으로 쿼리를 생성하는 책임을 명확히 나눈는게 단일책임원칙(SRP)을 더 잘 준수하게 된다고 생각해요 :)

2024-10-14 12:21 UTC, jongmin4943 commented on src/main/java/parse/ParseConfig.kt
> +    }
특정 Entity 클래스가 가진 필드가 어떤 `type` 인지, `GeneratedValue` 의 `strategy`는 무엇인지, `nullable` 인지 등등 정보를 가지고 있는 클래스들과, DB 종류에 따라 어떤 쿼리를 만들지를 결정하는 클래스들이 명확하게 나뉜다면 조금더 유연한 구조가 되지 않을까요? :)

2024-10-14 12:21 UTC, jongmin4943 commented on src/main/java/persistence/sql/QueryManagerFactory.kt
> +}
> 말씀하신대로 DB 종류에 따라 컬럼 타입을 구분해야 한다면 자바가 DB의 커넥션을 얻는 로직을 추상화하기 위해 [DataSource](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.sql/share/classes/javax/sql/DataSource.java) 인터페이스를 도입한 것과 같이 추상화를 통해 런타임에 구현체를 꽂아줘야할 것 같습니다.

현재는 간단하게 상위에서 어떤 DB 를 사용할지 하드코딩으로 주입해주는 모양만 잡아둬도 될 것 같아요 :)

<details>
  <summary>힌트</summary>  
실제 `Hibernate` 에서는 Dialect 라는 추상화를 통해서 DB 종류 별로 변하는 쿼리들을 관리하고 있어요.
</details>

> 혹시 말씀하신 DB 종류와 컬럼 사이즈 구별도 이번 단계에서 진행하면 될까요??

이후 미션인 DML 뿐만 아니라 만들면서 배우는 JPA 과정 내내 가져가실 구조를 만드는 과정이라 이번 단계에서 구조를 잡고 나가시는게 좋을 거라 생각해서 한번더 Request Change 드려요.

혹시 조금 과하다고 생각되신다면, 다음 미션 진행하면서 구조를 맞춰나가는 것도 괜찮으니 다음 미션 진행하면서 해보겠다고 편하게 말씀해주세요 ㅎㅎ 😃

2024-10-14 12:21 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/DefinitionQueryManagerTest.kt
> +import parse.ParseConfig
이 import 구문은 없어도 되는 것 같네요 :)

2024-10-14 12:21 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/TableTest.kt
> +import persistence.sql.ddl.table.Table
여기도 안쓰이는 import 가 있는데 확인 후 제거 해주시면 감사합니다 :)

2024-10-14 12:21 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/DefinitionQueryManagerTest.kt
> +        }
`Person1` 이라는 클래스도 추가해주셨는데, Person 과 Person1 둘다 어떤 쿼리가 나와야하는지 테스트를 추가해주시면 감사하겠습니다 🙇

2024-10-16 01:00 UTC, closed without merging