Step2
next-step/jpa-query-builder pull request #266
Opened 2024-10-13 13:31 UTC by hyeongyeong

2024-10-13 17:37 UTC, jongmin4943 requested changes
안녕하세요 현경님!

2단계 잘 진행해주셨네요 👍 몇 가지 고민해볼만한 코멘트 남겼는데 확인 후 재 요청부탁드려요 🙏

궁금하시거나 고민 되시는 부분이 있으시다면 언제든 코멘트나 DM 주세요! 🔥

2024-10-13 17:37 UTC, jongmin4943 commented on README.md
> +- [X] drop query 생성
README 는 다른 누군가가 읽을때, 하나의 문서가 된다고 생각해요 :)

필수는 아니지만, 조금 더 어떤 의도로 작성하셨는지 알 수 있게 자세히 적어주시면 좋을 것 같아요 👍

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +    private boolean trans;
사소하지만, 가능하다면 만들면서 배우는 JPA 과정 진행 중에 [객체지향생활체조](https://edu.nextstep.camp/s/BkhC9zSg/ls/ifdcwNoy)를 지키려고 노력해보시면 좋을 것 같아요 👍 

![image](https://github.com/user-attachments/assets/9b733af2-a123-4b92-8b6f-3438dce217bb)

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +    }
Column 들의 정보를 관리하는 `ColumnInfo` 클래스를 도출해내셨네요 💯

정적 팩토리 메서드를 제공할땐 생성자를 private 으로 지정해서 생성의 통제력을 강화해보면 어떨까요?

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +        if(field.isAnnotationPresent(Id.class)) {options.add("not null");}
사소하지만, 개인적으로 if문에 코드블럭을 명시해줘야 한다고 생각해요.

- if 문이 보이면 코드블럭을 예상하는데 1줄짜리인 경우, 코드블럭이 없어서 예상과 다른 부분으로 인해 가독성을 해친다고 느껴요.
- if 문은 코드블럭을 가진다. 라는 일관성을 지키는게 실수를 줄여준다고 생각해요.
- if 문 내부에 로직이 늘어나는 경우 블럭을 그때 추가하는 것 보단 미리 만들어 놓는게 나중에 코드리뷰를 해주는 사람 입장에서나 코드를 고치는 사람 입장에서 편하다고 생각해요.

현경님은 어떻게 생각하시나요?

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +        }
현재 `GenerationType` 이 `IDENTITY` 일때 `auto_increment` 로 고정되어 있는데,  `AUTO` 가 추가된 경우에는 DB 마다 전략이 바뀌어야 해요. 해당 부분은 어떻게 해결할 수 있을까요?

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnType.java
> +    ;
`ColumnType` 을 enum 으로 관리해주셨네요 👍

MySQL 에서는 Integer 가 `INT` 로 표현되기도 하고, 특정 DB 에서 String 은 `varchar2` 로 다룰수도 있을 것 같아요.
이런식으로 DB 마다 달라지는 부분은 어떻게 해결할 수 있을까요? 🤔

또한, varchar 의 길이도 Column 의 옵션 값으로 변경할 수 있어야 할 것 같아요 :)

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/QueryBuilderDDL.java
> +            throw new IllegalArgumentException("Entity로 정의되어 있지 않은 class를 입력하였습니다.");
`QueryBuilderDDL` 쿼리 생성을 담당할 것 같은데, 현재 Class 로 부터 정보를 추출과 검증하는 책임과 쿼리를 만드는 책임 두 가지가 섞여있어요 😢

Class 로 부터 정보를 추출해서 가지고 있는 `ColumnInfo` 를 좀 더 활용하면 좋을 것 같은데 `QueryBuilderDDL` 이 직접 생성하고 있네요. 🤔 

외부에서 미리 생성한 정보를 주입받는 형태가 되면 책임이 좀 덜어질 것 같은데 어떻게 생각하시나요? :)

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/QueryBuilderDDL.java
> +    }
가령 만들어주신 `ColumnInfo` 처럼 `TableInfo` 라는 클래스가 있다면, `TableInfo.getTableName` 과 같이 메시지를 주고받을 수 있을 것 같아요 😃

클래스명이나 메서드명은 참고만 부탁드려요 :)

2024-10-13 17:37 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/QueryBuilderDDL.java
> +    }
단순히 내부의 값을 getter 로 가져와서 사용하는 것이 아닌, `ColumnInfo` 에게 메시지를 전달하는 방식을 사용해보시는게 어떨까요?

[디미터의법칙](https://mangkyu.tistory.com/147)을 참고해보셔도 좋을 것 같아요 👍

2024-10-13 17:37 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/ColumnTest.java
> +    void createColumnClassWithPersonClass_id() throws Exception {
"Person Class로 Column 생성 : id" 라는 DisplayName 보단 좀 더 자세하게 이 테스트가 무엇을 나타내는지 표현이 되었으면 좋겠어요.

팀 단위로 테스트 주도개발을 하다보면, 수백 수천개의 테스트 코드를 돌리게 되는데, 테스트 실패 시 가장 많이 읽게 되는 부분은 실제 테스트 코드 보다도 결국 DisplayName 이더라고요. 😅

2024-10-13 17:37 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/ColumnTest.java
> +    }
이 두 테스트는 실패하네요 😭 코드를 수정 후 전체 테스트를 돌려보는 습관을 들여보시면 좋을 것 같아요 👍

![image](https://github.com/user-attachments/assets/a0cc5b26-0629-432c-b9d8-32151d5d5946)

2024-10-13 17:37 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/ColumnTypeTest.java
> +    }
테스트의 형태가 중복되는 것 같아요. 필요하다면 `@ParameterizedTest` 를 활용해보시는건 어떨까요?

마지막 검증부는 한줄로 줄일 수 있을 것 같아요
```diff
- assertAll(
-                () -> assertThat(columnDef.getQueryDefinition()).isEqualTo(ColumnType.BIGINT.getQueryDefinition()),
-                () -> assertThat(columnDef.getJavaType()).isEqualTo(ColumnType.BIGINT.getJavaType()),
-                () -> assertThat(columnDef.getQueryDefinition()).isEqualTo("bigint")
-        );
+  assertThat(columnDef).isEqualTo(ColumnType.BIGINT);
```

2024-10-13 17:37 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/QueryBuilderDDLTest.java
> +    }
개인적으로 테스트케이스가 조금 부족하다고 느껴져요. 😢

요구사항 1 일때 나오는 쿼리, 요구사항 2일때 나오는 쿼리, 요구사항 3 일때 나오는 쿼리가 조금씩 다 달라지는 부분에 대한 케이스들도 추가해주시면 감사하겠습니다 😃

2024-10-13 17:37 UTC, jongmin4943 commented on src/test/java/study/ReflectionTest.java
> +    }
피드백 반영해주셨군요! 감사합니다 😃

2024-10-14 13:10 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +    private boolean trans;
transient 같은 경우는 java에 이미 선언된 변수이기 때문에 다른 변수 이름을 선택하려다가 축약어를 사용하게 된 것 같습니다. 종민님은 보통 변수 이름이 다른 기능에 포함된 변수 이름과 겹치는 경우 어떤 식으로 네이밍을 하시는지 궁금합니다.

2024-10-14 13:12 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +    }
보통 builder 패턴에서 builder를 사용한 생성을 강제하기 위해 생성자를 private으로 설정하는 것으로 알고 있는데 같은 것으로 볼 수 있겠네요! 피드백 감사합니다.

2024-10-14 13:13 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +        if(field.isAnnotationPresent(Id.class)) {options.add("not null");}
코드를 짧게 쓰는게 좋을까 하고 최대한 짧게쓰려고 하다보니 가독성을 해칠 수도 있겠다는 생각을 놓친 것 같습니다. 피드백 감사합니다!

2024-10-14 17:34 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +    private boolean trans;
음 만약 제가 현재와 같은 상황이었다면, `isTransient` 라는 변수명을 사용했을 것 같아요. boolean 타입은 `is~` 로 만드는 습관을 가지고 있다보니 그런 것 같습니다. 만약 예약어와 겹친다면, 다르지만 비슷한 의미를 가지는 단어를 생각해볼 것 같아요. 이름 짓기가 항상 어렵긴 하죠 😅

2024-10-15 12:28 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +        }
고민을 해봤는데 AUTO가 추가된 경우에 DB마다 전략이 바뀌어야한다는 것을 이해하지 못했습니다. 혹시 힌트 부탁드려도 될까요?

2024-10-15 12:29 UTC, hyeongyeong commented on src/test/java/persistence/sql/ddl/ColumnTest.java
> +    }
전체 테스트 돌려보도록 노력하겠습니다! 감사합니다.

2024-10-15 12:30 UTC, hyeongyeong commented on src/test/java/persistence/sql/ddl/QueryBuilderDDLTest.java
> +    }
Test 코드에 Dummy class를 만들어 각각의 요구사항에 대하여 테스트를 진행하였는데 이렇게 테스트를 해도 괜찮을까요?

2024-10-15 13:16 UTC, hyeongyeong commented on src/test/java/persistence/sql/ddl/ColumnTypeTest.java
> +    }
@ParameterizedTest 를 종민님 덕분에 처음 알게되었는데 나중에 여러 값을 한 번에 테스트하고 싶은 경우에 사용해보겠습니다! 감사합니다.

2024-10-15 13:24 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +        }
`GeneratedValue.strategy` 에는 다양한 방식이 존재하는데 AUTO 는 이런 식으로 동작합니다. [참고링크](https://www.popit.kr/%ED%95%98%EC%9D%B4%EB%B2%84%EB%84%A4%EC%9D%B4%ED%8A%B8%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%9E%90%EB%8F%99-%ED%82%A4-%EC%83%9D%EC%84%B1-%EC%A0%84%EB%9E%B5%EC%9D%84-%EA%B2%B0%EC%A0%95%ED%95%98/) 

이것을 구현하라는 것이 아닙니다! 참고만 부탁드려요 ㅎㅎ
`GeneratedValue.strategy` 에는 다양한 방식이 존재하고, DB 종류가 바뀔때마다 ID 를 생성하는 방법이 바뀔 수 있습니다. 그런데 지금  `GenerationType.IDENTITY` 일때 `auto_increment` 로 고정된 형태라 드린 피드백이었습니다.

제 피드백의 방향은 전략패턴을 사용해서 풀어보라는 방향이었습니다만, 현재 요구사항으로는 존재하지 않는 부분입니다 ㅎㅎ.. 현경님이 잘해주셔서 제 욕심으로 생긴 과한 피드백이니 넘어가셔도 좋을 것 같습니다 :)

2024-10-15 13:25 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/QueryBuilderDDLTest.java
> +    }
넵! 아주 훌륭합니다 :)

2024-10-15 13:26 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/QueryBuilderDDL.java
> +            throw new IllegalArgumentException("Entity로 정의되어 있지 않은 class를 입력하였습니다.");
TableQueryBuilder와 ColumnQueryBuilder로 책임을 쪼개서 만들어봤는데 이렇게 사용하는 것에 어떻게 생각하세요?

2024-10-15 14:03 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/ColumnType.java
> +    ;
고민해보겠습니다!

2024-10-15 14:30 UTC, hyeongyeong commented on src/main/java/persistence/sql/ddl/ColumnType.java
> +    ;
Column의 옵션에 따라 길이 변경에 관련된 부분은 고민해보겠습니다!

2024-10-15 15:29 UTC, jongmin4943 approved these changes
안녕하세요 현경님!

2단계 피드백 반영 해주셨네요 👍  커밋을 잘 쪼개주셔서 생각의 흐름을 느낄 수 있었습니다! 💯 
많은 고민을 하시면서 만들어 나가시는게 느껴졌는데, 물어보신 부분들과 개선해보면 좋을만한 점들에 대해 코멘트 달아놓았으니 확인 부탁드릴게요! 🙇

2단계는 여기서 머지하겠습니다. 3단계 진행하시면서 피드백 참고 부탁드려요 😃

궁금하시거나 고민 되시는 부분이 있으시다면 언제든 코멘트나 DM 주세요! 🔥

2024-10-15 15:29 UTC, jongmin4943 commented on README.md
> +- [X] Person Class의 Drop Query 생성
피드백 반영 해주셨네요 👍

2024-10-15 15:29 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnInfo.java
> +    }
`ColumnInfo` 는 순수하게 Column 에 대한 정보만 다뤄야 할 것 같아요.

현재 이 메서드는 쿼리를 만드는 메서드라 `ColumnInfo` 가 가지고 있기에는 어색하다고 느껴지네요 😅

2024-10-15 15:29 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnQueryBuilder.java
> +    }
이 로직은 쿼리 생성의 책임을 가진 `ColumnQueryBuilder` 가 가지기에 조금 어색하다 느껴져요.

이 생성의 책임도 특정 클래스에게 맡겨보면 좋을 것 같아요.

<details>
  <summary>힌트</summary> 

Class 를 가지고 `List<ColumnInfo>` 를 만들어서 필드로 가지고 있는 객체가 있다면 어떨까요?
조금 더 구체적으로 힌트를 드리자면 일급컬렉션을 활용해보시는 것도 좋을 것 같아요.
참고 링크입니다.
<a href='https://jojoldu.tistory.com/412' target='_blank'>일급컬렉션이란<a>

</details>

2024-10-15 15:29 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/ColumnQueryBuilder.java
> +        }
위의 피드백이 반영된다면 이런 느낌의 코드가 가능하지 않을까요?
```suggestion
        List<ColumnInfo> primaryKey = columnInfos.getPrimaryKeys();
```

2024-10-15 15:29 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/JPAColumnType.java
> +    ;
`ColumnType` 를 추상화하고, enum 으로 구현해주셨네요 💯

DB 종류별로 어떤 타입으로 변환할지를 나타내주는 것 같은데, 구현체 이름에 DB 를 특정지어봐도 좋을 것 같아요 👍
ex) `MySQLColumntype`, `H2ColumnType`...

2024-10-15 15:29 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/TableQueryBuilder.java
> +    }
이 메서드도 마찬가지로 쿼리빌더 라는 이름을 가진 클래스가 가지기엔 어색한 작업 같아요 😢

중간에 커밋을 보니 `TableInfo` 라는 객체를 잘 분리해주셨더라구요. 그 당시 `TableInfo` 는 class 정보로부터 필요한 정보를  검증 및 추출하는 책임을 가지고, 쿼리빌더는 해당 클래스를 사용함으로써 적절하게 잘 분리가 되었었다고 생각해요 :)

<details>
  <summary>힌트</summary>  
쿼리빌더는 리플렉션이라는걸 아에 모르도록 만들어보는 것도 좋을 것 같아요.
</details>

2024-10-15 15:29 UTC, jongmin4943 commented on src/main/java/persistence/sql/ddl/TableQueryBuilder.java
> +    }
> TableQueryBuilder와 ColumnQueryBuilder로 책임을 쪼개서 만들어봤는데 이렇게 사용하는 것에 어떻게 생각하세요?

`TableQueryBuilder` 와 `QueryBuilderDDL` 의 차이점을 잘 모르겠어요. `QueryBuilderDDL` 는 그냥 메서드만 위임하는 약간 쓸모없는 클래스가 되어버린것 같아요 😢

2024-10-15 15:29 UTC, jongmin4943 commented on src/test/java/persistence/sql/ddl/QueryBuilderDDLTest.java
> +    public class DummyPerson3 {
요구사항별 테스트 케이스 추가해주셨네요 💯
조금 스포하자면 만들면서 배우는 JPA 과정 진행 중 기존 만들었던 코드들의 리팩토링 작업이 꽤나 많이 일어나요. 그때 테스트코드가 없으면 리팩토링하기 어려워지게 되니 테스트코드를 든든하게 짜놓으면서 진행하시는걸 권장 드립니다 :)

2024-10-15 15:29 UTC, merged