4단계 - Simple Entity Object
next-step/jpa-query-builder pull request #274
Opened 2024-10-14 15:34 UTC by jsyang-dev

안녕하세요. 정원님!
4단계 미션 리뷰 요청드립니다.

난이도가 갈수로 높아지는 것이 체감됩니다 🥹
코드를 볼 때마다 개선할 포인트들이 보여서 이번에도 리팩터링이 많았던 것 같네요.
지난번 미션에서 리뷰 주셨던 EntityField의 초기화 시점에 대한 부분도 반영하였습니다.

이번 리뷰도 잘 부탁드립니다 🙇

2024-10-14 17:16 UTC, jwee0330 requested changes
안녕하세요 정수님 🙂

업무도 바쁘실텐데 벌써 step4 까지 작업해 주시다니 정말 대단하세요!
요구사항을 깔끔하게 충족하도록 구현해 주셨습니다.
다만 몇 가지 고민해 보시면 좋을만한 부분을 코멘트로 남겨 놓았습니다.
살펴 보시고 수정 후 다시 PR 요청 부탁드립니다 🙇‍♂️ 

제 코멘트가 부족하거나 의견교환이 필요하실땐 DM 혹은 편하신 채널로 언제든 편하게 연락주세요 😁

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/entity/CustomRowMapper.java
> +                .getDeclaredMethod(entityField.getResultSetGetterName(), String.class);
getResultSetGetterName() 을 이용하는 아이디어가 너무 좋았습니다 👍 
다만 조금만 더 유연한 구조가 되었으면 좋겠습니다.
Java type -> SQL type
SQL type -> Java Type
간의 변화를 자유롭게 하기 위해서 새로운 자료구조를 생성해 보시는 것을 제안드립니다!

힌트를 드리자면.. 
`javax.sql.Type.class` , `ResultSetMetaData metaData = resultSet.getMetaData();`
를 한번 살펴 보시기 바랍니다.

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityManager.java
> +public interface EntityManager<T> {
이번 강의의 핵심인 JPA 스펙이 등장하네요 🙂
앞으로 과정 진행할때 `javax.persistence.EntityManager` 인터페이스를 꼼꼼히 살펴보시길 권장 드립니다!
많은 도움이 되실거라고 생각해요.

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        this.jdbcTemplate = new JdbcTemplate(H2ConnectionFactory.newConnection());
여러번에 걸쳐 리팩터링 된것을 보았습니다! 👍 

보면서 든 제 생각인데요,
커넥션 풀이 존재한다면 커넥션 생성이 아닌 풀에서 획득하는 구조로도 확장이 가능하도록 생성자 내부에서 객체 생성보다는
외부에서 주입받아 멤버 필드로 갖게 하는게 낫지 않을까? 라는 생각도 듭니다.

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/entity/InstanceFactory.java
> +    public static final String NO_DEFAULT_CONSTRUCTOR_FAILED_MESSAGE = "기본 생성자가 없습니다.";
정말 사소하지만 접근제한자는 필요에 맞도록..
package-private 으로 제안드립니다..!

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/example/Person.java
> +
피드백 반영 감사합니다 🙇‍♂️

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/sql/meta/EntityFields.java
> +    }
1급 컬렉션 활용 👍

2024-10-14 17:16 UTC, jwee0330 commented on src/main/java/persistence/sql/meta/FieldType.java
> +    STRING("VARCHAR(255)", true, "getString"),
`@Column(length = 5)` 와 같은 필드는 varchar(5) 타입으로 테이블이 생성 되려면 어떻게 해야 할까요?

2024-10-14 17:16 UTC, jwee0330 commented on src/test/java/persistence/entity/EntityManagerImplTest.java
> +        );
assertAll 활용 좋아요 :)

2024-10-15 12:47 UTC, jsyang-dev commented on src/main/java/persistence/entity/CustomRowMapper.java
> +                .getDeclaredMethod(entityField.getResultSetGetterName(), String.class);
좀더 유연한 방법이 있었는데 너무 무식한(?) 구조로 개발했네요ㅎㅎ

metaData.getColumnType() 을 사용하면 DB의 타입을 구할수 있었네요!
이걸 어떻게 활용할 수 있을지는 아직은 감이 안와서 좀 더 고민해봐야 할 것 같습니다 🤔

2024-10-15 12:50 UTC, jsyang-dev commented on src/main/java/persistence/entity/EntityManager.java
> +public interface EntityManager<T> {
기존 프레임워크의 코드들도 유심히 보는 습관을 길러야 겠네요!

2024-10-15 12:53 UTC, jsyang-dev commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        this.jdbcTemplate = new JdbcTemplate(H2ConnectionFactory.newConnection());
예리한 지적이십니다ㅎㅎ
지금은 H2 커넥션에 종속되어 있어서 확장이 어려운 구조라서, 이후 개선을 해야겠다고 생각은 하고 있었어요.

2024-10-15 14:21 UTC, jsyang-dev commented on src/main/java/persistence/sql/meta/FieldType.java
> +    STRING("VARCHAR(255)", true, "getString"),
length 도 고려해야 될 것 같네요!

2024-10-15 15:13 UTC, jsyang-dev commented
안녕하세요. 정원님!
코멘트 주신 내용 반영해서 리팩터링을 진행해보았습니다.
추가 리뷰 부탁드립니다 🙇

2024-10-15 16:44 UTC, jwee0330 approved these changes
안녕하세요 정수님!
일부러 힌트도 제한적으로 드렸는데, 척척 구현해 주셔서 놀랐습니다 👍 
워낙 잘하셔서 더이상 드릴 코멘트가 없네요 😅
정수님 코드를 보면서 저는 많은 인사이트를 얻었는데요
정수님도 저와 함께 했던 1주차 미션이 즐거우셨기를 바랍니다 😁
그럼 2주차 미션도 파이팅하세요 💪🏼

2024-10-15 16:44 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityManager.java
> +public interface EntityManager<T> {
이미 잘 알고 활용하고 계실거라고 생각합니다.. 🙂
조금이나마 이번 과정을 통해 뭔가 생각해볼거리를 드려보기 위해 코멘트 드려봤습니다..ㅎㅎ

2024-10-15 16:44 UTC, merged

2024-10-15 16:47 UTC, jwee0330 commented on src/main/java/persistence/entity/CustomRowMapper.java
> +                .getDeclaredMethod(entityField.getResultSetGetterName(), String.class);
저는 metaData.getColumnCount 를 활용해서 인덱스로 컬럼에 접근하도록 구현해 보았습니다.
참고가 되셨기를 바랍니다 :)

2024-10-15 16:48 UTC, jwee0330 commented on src/main/java/persistence/sql/meta/FieldType.java
> +    STRING("VARCHAR(255)", true, "getString"),
실제로 hibernate 는 제약조건도 추상화 하고 있다지요..?ㅎㅎ

2024-10-16 02:54 UTC, jsyang-dev commented on src/main/java/persistence/entity/CustomRowMapper.java
> +                .getDeclaredMethod(entityField.getResultSetGetterName(), String.class);
그런 방법도 가능하겠네요!
새로운 인사이트를 주셔서 감사합니다 🙏

2024-10-16 02:56 UTC, jsyang-dev commented on src/main/java/persistence/entity/EntityManager.java
> +public interface EntityManager<T> {
정원님의 코멘트 덕분에 생각해보거리가 많아져서 좋았던 것 같아요.
감사합니다! 🙇

2024-10-16 02:58 UTC, jsyang-dev commented on src/main/java/persistence/sql/meta/FieldType.java
> +    STRING("VARCHAR(255)", true, "getString"),
오호~ 추상화할 대상이 끝이 없네요 😂
hibernate 코드를 좀더 살펴보겠습니다

2024-10-16 04:42 UTC, jsyang-dev commented
이번주 미션을 진행하면서 많이 배울 수 있었고 인사이트도 많이 얻을 수 있었던 것 같아요.
정원님이 힌트를 잘 주셔서 미션도 빠르게 진행할 수 있지 않았을까요 👍
한주동안 감사했습니다! 🙇 🙇 🙇