Step2 피드백 반영
next-step/jpa-query-builder pull request #288
Opened 2024-10-16 14:23 UTC by jeseungkim

스텝2 피드백 반영입니다!
상세한 피드백 정말 감사합니다 ㅠㅠ
수정하면서 성장한거같아요!!!

그리고 pr을 보고 올렸는데.. 왜잘안올라갔을까요 ...ㅠㅠ 
다시한번올려보겠습니다!

2024-10-16 16:53 UTC, leeyohan93 requested changes
안녕하세요 제승님! 😄 
피드백을 잘 반영해주셨네요 💯 
다음 단계 미션으로 넘어가기 전에 한번 더 개선해보면 좋을만한 부분이 있어 코멘트 남겨드렸습니다!
궁금하신 부분이나 어려우신 부분이 있다면 편하게 DM 보내주세요!
오늘은 저녁에 수업이 있는 날이네요~ 화이팅입니다! 🔥

2024-10-16 16:53 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/MySqlTypeMapper.java
> +public class MySqlTypeMapper implements SqlTypeMapper{
앗 제가 예시를 MySQL과 Postgress로 드려서 구현체를 두개 만들어주신 것 같아요!
저희 미션에서는 H2 데이터베이스를 사용하기 때문에 H2로 만들어주시면 좋을 것 같습니다 😄

2024-10-16 16:53 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/MySqlTypeMapper.java
> +    }
if 문을 사용하게 되면 새로운 타입의 지원이 추가되었을 때 조회 코드를 수정해야하는 단점이 있는데요!
Map과 같은 자료구조를 사용해보는 것은 어떨까요? :)

2024-10-16 16:53 UTC, leeyohan93 commented on src/test/java/persistence/sql/ddl/QueryBuilderTest.java
> +public class QueryBuilderTest {
현재 QueryBuilder의 가장 중요한 기능은 create와 drop 쿼리를 만드는 것인데요!
해당 테스트는 꼭 챙겨주시면 좋을 것 같습니다 :)

2024-10-16 16:53 UTC, leeyohan93 commented on src/test/java/persistence/sql/ddl/QueryBuilderTest.java
> +        QueryBuilder queryBuilder = new QueryBuilder(Person.class, sqlTypeMapper);
sqlTypeMapper 변수를 선언해주셨는데 해당 값에 초기화가 되지 않아 null로 적용되고 있네요! 
필요하지않은 변수라면 제거해주셔도 좋을 것 같습니다 :)

2024-10-16 16:53 UTC, leeyohan93 commented on src/test/java/persistence/sql/ddl/PersonTest.java
> +    }
모든 테스트는 assertj 를 사용해서 검증해주시면 좋을 것 같아요 :)
println과 같은 시스템 출력은 항상 테스트가 성공하기 때문에 동작이 잘못되어도 테스트가 성공될 수 있습니다!

2024-10-16 16:53 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +    }
1. sqlTypeMapper 를 만들어주셨지만 실제로 동작하는 코드에서는 해당 메서드를 통해서 타입을 변환하고 있네요!
sqlTypeMapper을 통해 SQL Type을 구할 수 있도록 수정해주시면 좋을 것 같습니다 :)

2. NotNull 어노테이션은 제거해주셔도 좋을 것 같아요!
메서드가 null을 반환할 것을 기대하지 않게 개발하는 것이 좋기 때문인데요! 만약 어쩔 수 없이 null을 반환해야하는 경우 Optional을 사용함으로 써 구현할 수 있습니다!

2024-10-16 16:53 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +    }
일부 불필요한 static 선언은 모두 제거해주셔도 좋을 것 같습니다!

```suggestion
    private String getPrimaryKey(Field field) {
        if (field.isAnnotationPresent(Id.class) == true) {
            return " PRIMARY KEY";
        }
        return "";
    }
```

2024-10-16 16:53 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +        return query.toString();
자바의 stream을 사용해서 표현해보면 아래와 같이 구현 해볼 수도 있습니다! 😄 

```suggestion
        return Arrays.stream(clazz.getDeclaredFields())
                .filter(field -> !field.isAnnotationPresent(Transient.class))
                .map(field -> getColumnName(field) + " " + getSqlType(field) + getPrimaryKey(field) + getAutoIncrement(field) + getNullable(field))
                .collect(Collectors.joining(", "));
```

2024-10-18 12:34 UTC, jeseungkim commented
말씀해주신대로 수정 다 했습니다! 이제야 제법 괜찮은 코드처럼 보이네요! 정말 감사합니다!

2024-10-18 16:08 UTC, leeyohan93 approved these changes
안녕하세요 제승님 😄 
피드백을 꾸준하게 잘 반영해주셔서 코드가 많이 깔끔해진 것 같습니다! 💯 
다음 단계를 진행하시면서 함께 반영해보시면 좋을 부분들에 코멘트를 남겨드렸으니 확인 부탁드릴게요 :)
궁금하신 점이나 고민되는 부분은 편하게 DM, 코멘트로 남겨주세요!
좋은 주말 되세요! 🙏

2024-10-18 16:08 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/H2SqlTypeMapper.java
> +    }
자바의 타입을 문자열 대신 클래스를 사용해보면 타입 안정성을 가져갈 수 있을 것 같아요! :)

```suggestion
    Map<Class<?>, String> sqlType;

    public H2SqlTypeMapper() {
        sqlType = new HashMap<>();
        sqlType.put(Long.class, "BIGINT");
        sqlType.put(String.class, "VARCHAR(255)");
        sqlType.put(Integer.class, "INT");
    }
```

2024-10-18 16:08 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +    }
아래와 같이 String.format()을 이용하고 쿼리 포맷 문자열을 상수로 관리해보는 것도 좋을 것 같아요 :)

```java
    private static final String CREATE_QUERY_FORMAT = "CREATE TABLE %s(%s)";
    public String create() {
        return String.format(CREATE_QUERY_FORMAT, getTableName(), getPersonMetadata());
    }
```

2024-10-18 16:08 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +    SqlTypeMapper sqlTypeMapper;
지금의 `QueryBuilder` 에서는 하나의 Class 타입 만을 쿼리로 만들 수 있는 구조인데요!
클래스를 쿼리를 만드는 메서드의 파라미터로 전달받도록 개선해보면 어떨까요? :)
```java
public String create(Class<?> clazz);
public String drop(Class<?> clazz);
```

2024-10-18 16:08 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +    }
static이 아직 설정되어 있는 부분이 있네요! 👀 

```suggestion
    private String getAutoIncrement(Field field) {
        if (field.isAnnotationPresent(GeneratedValue.class) == true) {
            return " AUTO_INCREMENT";
        }
        return "";
    }
```

2024-10-18 16:08 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +    public String getPersonMetadata() {
1. 객체 내부에서만 사용하는 메서드들은 접근제어자를 private으로 설정해주시면 좋습니다! 👍 

2. 메서드 이름이 특정 클래스에 종속되면 코드의 유연성과 재사용성이 떨어지기 때문에 메서드가 하는 일을 잘 표현할 수 있도록 바꿔주시는 것이 적절할 것 같습니다!

```suggestion
    private String getColumnQueries() {
```

2024-10-18 16:08 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +public class QueryBuilder {
QueryBuilder의 로직을 잘 개선해서 처음 코드 대비 굉장히 잘 작성해주셨어요! 💯 
다만 더 객체지향과 관련된 도전해보아야할 부분들이 남아있기도 합니다.
2주차 수업을 들으셨다면 강사님이 객체의 책임을 분리해나가는 라이브 코딩을 함께 보셨을 것 같은데요!
다음 단계에서는 책임을 분리하여 클래스를 분리하는 연습도 함께 해보시면 굉장히 많은 도움이 될 것 같습니다! 😄

2024-10-18 16:08 UTC, merged