[Step4] 4단계 - Simple Entity Object
next-step/jpa-query-builder pull request #291
Opened 2024-10-17 08:05 UTC by chanho0912

안녕하세요 진영님 😄
4단계 - Simple Entity Object 구현 리뷰 부탁드립니다!

이번에도 잘 부탁드립니다!!

2024-10-17 15:23 UTC, jinyoungchoi95 requested changes
안녕하세요 찬호님 😄

미션 잘 진행해주셨네요 👍 몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +            final JdbcTemplate jdbcTemplate = new JdbcTemplate(databaseServer.getConnection());
`JdbcTemplate`을 메소드 호출이 될때마다 매번 생성할 필요가 있을까요?

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        return entity;
1. 실제 `EntityManager` 스펙은 반환타입이 `void`인데요. `Object` 반환을 선택하신 이유가 있으실까요?
2. `Object`로 나간다면`@Id`의 생성 전략이 `IDENTITY`와 같은 자동 생성 전략이라면 생성된 id가 담긴 entity가 나가야하지 않을까요?

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        final String query = deleteByIdQueryBuilder.build(entity.getClass(), id);
remove요청에서 이런 복잡한 요청은 모두 제거하는건 어떨까요? 지금까지 잘 설계된 도메인 코드를 바라보면,
1. deleteByIdQueryBuilder.build 에서는 entity를 받는다.
2. 기존처럼 `TableDefinition`를 entity.getClass()로 생성한다.
3. `TableId`에서 id를 추출한다.
    a. 56번줄의 if문이 없어도 id의 값이 없으면 `ColumnDefinition`에서 값을 꺼내올 때 예외가 터지도록 설계되어있다.

마지막 단계인 `EntityManager`의 목표는 간단한 구조를 만들기이기 때문에 별다른 로직없이 잘 만들어주신 도메인 코드를 사용한다면 각 메소드마다 2~3줄로 끝나는 것이 목표인데요. 위 로직들은 모두 도메인 코드에 잘 담아두셨으니 제거해보는건 어떨까요?

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        // Entity Manager를 통해 기존의 entity를 가져옴.
해당 미션은 jpa를 만드는 것이 목표이기도하지만 객체지향과 클린코드도 목표 중 하나인데요. 주석으로 설명하는것은 물론 좋으나 최대한 현재 미션기간동안은 주석을 모두 지우고도 적절한 메소드 분리 등으로 코드만으로도 설명을 할 수 있는 구조로 만드는 것을 권장드려요 :)

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/query/UpdateQueryBuilder.java
> +    private final Map<String, String> conditions = new LinkedHashMap<>();
`EntityManager`는 entity에 대한 식별을 항상 id로 하기 때문에 condition이 여러개일 필요는 없습니다.

spring-data-jpa와 혼동이 오실 수 있는데, `EntityManager` 스펙에서의 find도 마찬가지로 특정 entity에 대한 식별은 항상 id로 만하므로 map은 제거해주시는 것이 좋을 것 같네요 :)

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/query/UpdateQueryBuilder.java
> +    }
이렇게 addColumn을 하면 `UpdateQueryBuilder`는 다른 entity는 재사용하지 못하는 클래스가 될 것 같아요. 의도치 않은 호출로 다른 entity가 들어오거나 column추가가 누락될 수 있구요.

이전에 했던 이야기의 연장선일 수 있는데 `QueryBuilder`들의 형태는 모두 동일하면 좋을 것 같아요. 어떤 `QueryBuilder`는 싱글톤, 어떤 `QueryBuilder`는 entity마다 생성하여 상태를 가지면 `QueryBuilder`라는 클래스를 사용하는 사람 입장에선 혼동이 올 것 같아요 🤔

2024-10-17 15:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +    private List<? extends Queryable> checkDirtyColumns(Object newEntity, Object persisted) {
다음 단계의 미션에서 다루는 내용이나 Dirty Check는 `EntityManager`에서 관리하기에는 많은 책임이에요. 구현 내용에서도 find 호출보다는 아실 수 있는 내용인 영속성 컨텍스트에 대한 개념이 들어가기도 하구요.

해당 단계는 `EntityManager`에 대한 간단한 설계를 목표로 하고 있고, 이후 단계에서 요구사항으로 더 자세하게 나와있으니 이부분은 일단 넘어가시면 좋을 것 같아요 😄

2024-10-18 01:08 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +            final JdbcTemplate jdbcTemplate = new JdbcTemplate(databaseServer.getConnection());
아, 넵넵 JdbcTemplate을 받는것이 낫겠군요.

2024-10-18 01:21 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        return entity;
우선 현 요구사항에서 조금 벗어난것같아서 void를 반환타입으로 지정하겠습니다 !

2024-10-18 01:29 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +    private List<? extends Queryable> checkDirtyColumns(Object newEntity, Object persisted) {
아 넵넵, 제가 너무 생각이 많았군요, 
updateQueryBuilder도 기존처럼 간단하게 있는 column들에 대해 update하는 것으로 수정 하고 이부분도 기존처럼 간단하게 처리하도록 수정해두겠습니다!

2024-10-18 01:29 UTC, chanho0912 commented on src/main/java/persistence/sql/dml/query/UpdateQueryBuilder.java
> +    private final Map<String, String> conditions = new LinkedHashMap<>();
넵 수정하도록 하겠습니다!

2024-10-18 12:35 UTC, jinyoungchoi95 approved these changes
안녕하세요 찬호님 😄

미션 수고하셨습니다 👍 
다음 단계도 화이팅하세요!

감사합니다 🙇‍♂️

2024-10-18 12:35 UTC, jinyoungchoi95 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +    }
👍

2024-10-18 12:35 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/query/DeleteByIdQueryBuilder.java
>          query.append(" WHERE id = ");
column명은 id가 아닐 수 있기 때문에 entity에서 추출한 id column의 이름이 들어가야할 것 같네요 :)

2024-10-18 12:35 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/query/UpdateQueryBuilder.java
> +        query.append(" WHERE id = ");
여기도 마찬가지입니다 😄

2024-10-18 12:35 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/query/UpdateQueryBuilder.java
> +                    return column.name() + " = " + columnValue;
stream이 나온 이유는 함수형 프로그래밍을 목표로 하고 있고, 익명함수로 표현될 수 있기는 하지만 행위자체를 더 잘 전달하고자한다면 메소드로 분리하고 메소드명만으로 이 stream을 알아볼 수 있도록 하는 것이 가독성을 더 직관적으로 만들어주어요.

2024-10-18 12:35 UTC, merged

2024-10-18 15:13 UTC, chanho0912 commented on src/main/java/persistence/sql/dml/query/DeleteByIdQueryBuilder.java
>          query.append(" WHERE id = ");
앗! 감사합니다 ㅎㅎㅎㅎ