Step4 - Simple Entity Object
next-step/jpa-query-builder pull request #297
Opened 2024-10-19 13:07 UTC by min-queue

안녕하세요 강태화 리뷰어님 ! 
step4마무리 지었습니다. 
아 이번 미션은 정말 힘들었던거 같습니다. 
어떻게 해야할지 한참 고민하면서 작업했던거 같습니다. 

따끔하게 리뷰 부탁드립니다 ! 감사합니다 ! :)

2024-10-20 01:57 UTC, wooobo requested changes
안녕하세요! 민규님

4단계에서 많은 고민을 하셨군요! ㅎ
몇가지 코멘트 남겨 놓았는데 확인 부탁드려요~
궁금한점 있으시면 DM주세요~

그럼 좋은 하루 되세요~

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +public class FakeEntityManager implements EntityManager {
Fake 는 테스트 코드에서 사용할법한 이름일것 같아요.
DefalutEntityManager 이런 형태의 이름은 어떤가요?

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +            jdbcTemplate.update(updateQuery);
jdbcTemplate 의 책임과 역할은, 간락하게 이렇게 볼수 있을것 같아요.
- SQL 쿼리 실행
- 데이터 액세스 계층과 데이터베이스 사이의 중간 계층

그렇다면, update보다는 실행한다는 책임을 명확하게 하기 위해서 `jdbcTemplate.executeUpdate(updateQuery);` 이런 방향으로 고민해볼것 같아요.

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +            jdbcTemplate.update(updateQuery);
`jdbcTemplate.update` 메소드의 구현을 완성해주시지 않았네요 😄 

좀 더 쉽게 접근하기 위해서, `jdbcTemplate.execute`을 활용해도 충분하지 않을까요?
`jdbcTemplate.update`를 사용하려고 했던 이유가 무엇인가요~?

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +        Map<Long, Object> table = fakePersistContext.get(clazz);
엇 지금은 1주차 미션 아닌가요 ^^;;
현재 단계에서는 `fakePersistContext`까지는 필요없을것 같아요.

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +return query.isEmpty() ? null : clazz.cast(query.get(0));
하나를 가져와야 하는 것이라면, `queryForObject`메소드가 어울리지 않을까요?

객체와 메소드 각각의 책임과 역할이 무엇일지 고민해보시는것도 좋을것 같아요~

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/entity/EntityRowMapper.java
> +    String getColumnName(Field field) {
접근제어자를 활용해보아요~

접근제어자는 왜 중요할까요?
private, public 둘중 무엇을 사용하면 좋을까요?

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/sql/dml/SelectQueryBuilder.java
>  import jakarta.persistence.Table;
사용하지 않는 불필요한 import는 제거하는게 좋지 않을까요?
사용하게 될때 import를 추가하는건 어떨까 생각이되는데 이부분에 대해서 어떻게 생각하시나요~?

2024-10-20 01:57 UTC, wooobo commented on src/main/java/persistence/sql/dml/SelectQueryBuilder.java
> +        String tableName = getTableName();
`Table`관련 상태를 관리하는 객체가 있다면, `table 이름이 뭐야?`라고 물어볼수 있지 않을까요?

예를들면:
```java
        TableMeta tableMeta = TableMeta.from(entityClass);
        String tableName = tableMeta.테이블이름은?();
```

이런식의 접근은 어떤가요?

2024-10-20 06:20 UTC, min-queue commented on src/main/java/persistence/sql/dml/SelectQueryBuilder.java
> +        String tableName = getTableName();
한번 접근해보겠습니다 !!

2024-10-20 14:38 UTC, min-queue commented on src/main/java/persistence/sql/dml/SelectQueryBuilder.java
> +        String tableName = getTableName();
최대한 접근 해보려고 노력했습니다. 
지금 리팩토링 하고나서보니 DML쪽도 Value를 더 넣고 싶은데.. 
혹시 팁을 조금 주실 수 있을까요 ? 
제가, 일단 커밋은 해두었습니다.

2024-10-21 11:57 UTC, min-queue commented on src/main/java/persistence/entity/EntityRowMapper.java
> +    String getColumnName(Field field) {
변경완료했습니다!!

2024-10-21 11:57 UTC, min-queue commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +        Map<Long, Object> table = fakePersistContext.get(clazz);
넵 알겠습니다 삭제했습니다!

2024-10-21 11:58 UTC, min-queue commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +public class FakeEntityManager implements EntityManager {
변경 완료했습니다!

2024-10-21 12:00 UTC, min-queue commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
> +            jdbcTemplate.update(updateQuery);
아 당시에는 뭔가 update쿼리니까 update를 만들어서 하면 좋지 않을까? 라는 관점이었습니다. 
뭔가 다시 코드로 보니 어짜피 쿼리를 실행시키는 관점에선 상관이 없겠다 싶어서 삭제했습니다.

2024-10-21 14:33 UTC, wooobo requested changes
안녕하세요 민규님!

많은 고민을 해주셔서 감사합니다!
몇가지 코멘트 남겨 놓았어요~
확인 후 재요청 부탁드려요~ 🙏 

그럼 화이팅입니다!

2024-10-21 14:33 UTC, wooobo commented on src/main/java/domain/Person.java
> +
```suggestion
```

불필요한 공백 또한 제거하는게 아주 중요하다고 생각합니다 🙏

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/TableId.java
> +    private boolean isAutoIncrement;
```suggestion
    private final Class<?> type;
    private final String name;
    private final boolean isAutoIncrement;
```

`final`을 추가함으로써 **불변성 보장**, **코드 안정성**, **동시성** 측면에서 이점을 얻을 수 있을 것 같습니다. 초기화 이후 값이 변하지 않는 속성이라면, `final`을 적용해 추후 리팩토링 시 값이 의도치 않게 변경되는 것을 방지하는 것이 좋겠습니다!

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/TableId.java
> +    private static boolean isAutoIncrement(Field field) {
여기만 **static** 인데 이유가 있나요?

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/TableColumn.java
> +        this.name = setColumnName(column);
`setColumnName`은 ColumnName을 변경하라는 의미로 보통 알아볼것 같아요. 
그래서 `set-`은 **return**이 보통 없죠.
좀 더 의미 있는 이름 없을까요?

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/TableColumn.java
> +        this.name = setColumnName(column);
기본 생성자와 부생성자에 대해 알아보아요!

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/TableColumn.java
> +    public String getColumnName() {
값을 단순히 반환하는 역할이라면, 저는 `TableColumn.name()`과 같은 방식으로 메서드를 정의하는 것이 더 적절하다고 생각합니다.
이는 객체지향적 사고에 다가가기 위한 접근입니다. **get-** 접두어를 사용하면 메서드가 단순한 데이터 전달에 그칠 수 있지만, 명확한 이름을 사용하면 객체를 단순한 자료구조가 아닌, 책임과 역할을 가진 객체로 대우하는 데 도움이 됩니다.

`get-`을 뺀다고 이상한가요? 어쩌면 관습대로 그냥 붙이고 있던거 아닐까요?
그럼 `isNotNullable()`메소드는 왜 `getIsNotNullable()`이렇게 하지 않는걸까요?

무조건 `get-`을 사용하면 안된다는것은 절대 아닙니다. 한번쯤 고민해보셔도 좋을것 같아서요.

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/TableColumn.java
> +    private final boolean isNotNullable;
사람은 부정보다 긍정을 잘 이해한다고 해요.
그런 측면에서 `isNotNullable` => `isNullable` 어떤가요?

`TableColumn.null불가능?()` => `TableColumn.isNotNullable()` 전 메소드로 표현했을것 같아요.

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/sql/ddl/CreateTableQueryBuilder.java
> +        return CREATE_TABLE + tableMeta.getTableName() + " ("+ idColumn + columns + ");";
```suggestion
        String tableName = tableMeta.getTableName();
        String idColumn = createIdColumn(tableMeta.getTableId());
        String columns = createColumns(tableMeta.getTableColumn());

        return String.format("%s%s (%s%s);", CREATE_TABLE, tableName, idColumn, columns);
    }
```

좀 더 잘 읽히지 않나요?
함수가 복잡해진다면, 로직별로 메소드로 분리시켜보면 좋아요. 
중요한점은 로직이 의미하는것을 메소드 이름으로 잘 정의하는것이에요.

2024-10-21 14:33 UTC, wooobo commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
>      final Class<?> clazz;
```java
        EntityManager em = createEntityManager();

        Product product = new Product("Smartphone", 800.00);
        Order order = new Order("John Doe");

        em.persist(product);
        em.persist(order);
```

EntityManager를 활용한 간단한 예시코드입니다.
`final Class<?> clazz;`를 내부 상태로 가져가는게 맞을까요?
EntityManager는 어떠한 역할과 책임이 가지나요?

2024-10-21 15:45 UTC, min-queue commented on src/main/java/persistence/entity/impl/FakeEntityManager.java
>      final Class<?> clazz;
EntityManager의 역활은 영속성 컨텍스트를 관리하고
책임은 엔티티 상태관리에 있습니다, 데이터 정합성 보장(트랜잭션)  아 이해했습니다. 감사합니다 리뷰어님 :)

2024-10-21 15:51 UTC, min-queue commented on src/main/java/persistence/sql/ddl/CreateTableQueryBuilder.java
> +        return CREATE_TABLE + tableMeta.getTableName() + " ("+ idColumn + columns + ");";
따로 메서드로 분리하도록 하겠습니다!

2024-10-21 15:53 UTC, min-queue commented on src/main/java/persistence/sql/TableColumn.java
> +        this.name = setColumnName(column);
setColumnName() ->  columnNamae()  이런식으로 하는게 의미 전달이 더 잘될까요 ? : ) 
기본생성자 추가하도록하겠습니다!

2024-10-23 05:44 UTC, wooobo requested changes
안녕하세요 민규님!

몇가지 코멘트 남겨놓았는데, 코드 변경은 크게 안해주셔도 됩니다~
확인만 해주시면 될것같아요~
확인 후 재요청 부탁드려요~ 🙏 

그럼 좋은 하루되세요~

2024-10-23 05:44 UTC, wooobo commented on src/main/java/jdbc/JdbcTemplate.java
> +    public Long executeInsert(final String sql) {
executeInsert 메소드를 호출하는 입장에서, 반환값이 Long 타입일 경우 그 의미가 명확하지 않을 수 있습니다. 개선하기위해서 다음과 같은 고민을 해볼것 같아요.

1. 리턴 타입을 명확하게 지정하기
  - TableId와 같은 구체적인 타입 사용: Long 대신 TableId와 같은 도메인에 특화된 타입을 반환하면, 메소드를 사용하는 입장에서 해당 메소드가 삽입 후 생성된 ID를 반환한다는 것을 보다 쉽게 인식할 수 있습니다.

2. Long 타입을 유지할 경우 메소드 이름을 구체화하기
  - 반환 타입을 변경하지 않고 Long을 유지하려면, 메소드 이름을 executeAndReturnGeneratedKey와 같이 변경하여 반환되는 값의 목적을 명확하기

2024-10-23 05:44 UTC, wooobo commented on src/main/java/persistence/sql/TableColumn.java
> +        this.name = setColumnName(column);
- resolveColumnName
- extractColumnName

저는 이런것들이 떠오르네용 🤔

2024-10-23 05:44 UTC, wooobo commented on src/main/java/persistence/sql/ddl/CreateTableQueryBuilder.java
> +                H2DBDataType.castType(column.type()) +
`H2DBDataType` 같은 H2 데이터베이스에 맞추어 쿼리를 빌드하고있네요
그렇다면 `DefaultTableSchemaBuilder`, `H2TableSchemaBuilder` 이런 고민도 해볼수 있겠네요.

모든 코멘트에 대해 변경해주실필요는 없어요~ 
고민해보셔도 좋을것 같습니다!

2024-10-23 05:44 UTC, wooobo commented on src/test/java/persistence/entity/impl/DefaultEntityManagerTest.java
> +        Person foundPerson = entityManager.find(Person.class, 1L);
> 테스트 코드가 실패되고 있네요 😂 

비즈니스 코드가 변경되면 이에 맞춰 테스트 코드도 반드시 수정해야 합니다. 테스트 코드를 업데이트하지 않으면 테스트 실패는 물론, 향후 시스템의 안정성에도 문제가 발생할 수 있습니다. 
따라서 코드 변경 시 테스트 케이스를 꼼꼼히 검토하고 필요한 수정을 통해 일관성을 유지하는 것이 중요하다고 생각해요 😄

2024-10-23 05:44 UTC, wooobo commented on src/main/java/persistence/entity/impl/DefaultEntityManager.java
> +        Object cachedEntity = entityMap == null ? null : entityMap.get(id);
```suggestion
    public <T> T find(Class<T> clazz, Long id) {
        Map<Long, Object> entityMap = entityCache.get(clazz);
        T cachedEntity = entityMap == null ? null : clazz.cast(entityMap.get(id));
```

타입 안전성과 안전한 캐스팅을 위해 제네릭 타입을 더욱 견고하게 만드는 것이 좋을 것 같아요. 🤔  

예를 들어 `Person.class`를 전달하면 `Person` 객체를 반환하도록 명시하면, 호출하는 측에서 반환되는 객체의 타입을 확실하게 알 수 있어요. 현재는 **반환 타입**이 `Object`이기 때문에, 호출자가 원하는 타입의 객체를 받을 것이라는 보장이 없어요. 
제네릭을 좀더 견고하게 사용할 방법이 없는지 고민해보시면 좋을것 같아요!

2024-10-24 02:05 UTC, wooobo approved these changes
안녕하세요 민규님!

4단계까지 잘 진행해주셨습니다!
충분히 많은 고민이 진행된것 같아서 
이만 `merge`진행하겠습니다!

남은 미션도 화이팅입니다!

2024-10-24 02:05 UTC, wooobo commented on src/main/java/persistence/entity/impl/DefaultEntityManager.java
> +    public <T> Optional<T> find(Class<T> clazz, Long id) {
`Optional`을 잘 활용해주셨네요 👍 
`null`이 가능하다는 것을 명확하게 전달 되겠네요 좋아요. 😄 

추가적으로 JSR스펙과 하이버네이트 코드를 첨부해봤어요. 한번 살펴 보시면 좋을것 같아서 아래 댓글에 첨부해봤어요.

JSR스펙은 `API를 정의하고 표준화하기 위해 제안되는 명세`입니다. , 쉽게 말하면 `표준화된 스펙`입니다. 이 스펙에 맞추어 구현체를 만들면 JPA의 표준을 따르게 됩니다. 따라서 JPA 스펙에 맞는 인터페이스를 구현하면 코드의 호환성과 이식성이 높아질 수 있습니다.

> 너무 복잡한 의미로 해석하지 않았으면해요! ㅎ

2024-10-24 02:05 UTC, wooobo commented on src/main/java/persistence/entity/impl/DefaultEntityManager.java
> +    public <T> Optional<T> find(Class<T> clazz, Long id) {
## JSR338스펙
<img width="1120" alt="스크린샷 2024-10-24 오전 10 38 37" src="https://github.com/user-attachments/assets/5aa21ea8-a2d1-4282-bda8-cd75b77c90fd">

## 하이버네이트 find함수 예외처리 혹은 null처리 코드
<img width="991" alt="스크린샷 2024-10-24 오전 10 48 28" src="https://github.com/user-attachments/assets/16b8bf4b-40a3-4b96-b13f-a5ccb923863e">

### 번역
```java
catch ( FetchNotFoundException e ) {
    // 엔티티가 @NotFound(action = NotFoundAction.EXCEPTION)으로
    // 매핑된 연관 관계를 가지고 있고 이 연관된 엔티티를 찾을 수 없을 때 발생할 수 있습니다.
    throw e;
}
catch ( EntityFilterException e ) {
    // 엔티티가 FilterDef로 필터링된 연관 관계를 가지고 있고 이 연관된 엔티티를 찾을 수 없을 때 발생할 수 있습니다.
    throw e;
}
catch ( EntityNotFoundException e ) {
    // 우리는 다른 종류의 EntityNotFoundException을 처리하고 null을 반환합니다.
    // 예를 들어, DefaultLoadEventListener.proxyImplementation()은
    // 세션에 기존 프록시가 있지만 기본 데이터베이스 행이 삭제된 경우
    // EntityNotFoundException을 발생시킵니다 (HHH-7861 참고).
    logIgnoringEntityNotFound( entityClass, primaryKey );
    return null;
}
catch ( ObjectDeletedException e ) {
    // 동일한 Persistence Context에서 remove()와 find()를 동시에 수행하는 경우에 대한 사양은 명시되어 있지 않습니다.
    return null;
}
```

2024-10-24 02:06 UTC, merged