🚀 4단계 - Simple Entity Object
next-step/jpa-query-builder pull request #311
Opened 2024-11-02 06:08 UTC by sang5c

감사합니다 :)

2024-11-02 06:15 UTC, sang5c reviewed
고민했던 부분들입니다!

2024-11-02 06:15 UTC, sang5c commented on src/main/java/persistence/sql/metadata/ColumnData.java
> +public class ColumnData {
Value에 대한 필요가 계속 있어서 Column과 ColumnValue를 조합해서 갖는 형태로 구성해봤습니다.

2024-11-02 06:15 UTC, sang5c commented on src/main/java/persistence/sql/metadata/ColumnMetadata.java
> +    public List<ColumnData> withData(Object entity) {
ColumnData와 ColumnMetadata와의 연결을 어떻게 맺을지 고민하다 생성에 대한 책임만 맡겨봤습니다.

2024-11-02 06:15 UTC, sang5c commented on src/main/java/persistence/sql/metadata/EntityData.java
> +    private final List<ColumnData> columnDataList;
ColumnData도 이렇게 Metadata를 직접 가져야 할까 고민하다가, 연결이 애매하다고 느껴 다른 형태를 가지게 됐습니다.

2024-11-02 08:00 UTC, jongmin4943 requested changes
안녕하세요 상오님! 

마지막 4단계 미션 잘 진행해주셨네요 💯 
몇 가지 제 의견을 코멘트로 남겨두었습니다. 피드백 반영 후 재 요청 부탁드립니다. 🙇 

궁금한 사항은 언제든 추가 코멘트 또는 DM 주세요! 😃

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +public class EntityManagerImpl<T> implements EntityManager<T> {
`EntityManager` 를 잘 만들어주셨네요 💯

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        DmlQueryBuilder dmlQueryBuilder = new DmlQueryBuilder();
모든 메서드가 `DmlQueryBuilder` 를 매번 생성하고 있는데 상태로 가져도 괜찮지 않을까요? :)

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
> +                + ";";
select 쿼리를 만들때 * 대신에 필요한 필드를 지정해서 select 하도록 만들어 보시는건 어떨까요? :)

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
> +                + ";";
Java15 에 추가된 [Text block](https://www.baeldung.com/java-text-blocks) 을 이용해봐도 좋을 것 같아요 :)
```suggestion
        return """
                select * \
                from %s \
                where %s = %s;\
                """.formatted(metadata.getTableName(), metadata.getPrimaryKeyName(), id);
```

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
> +        List<ColumnData> columns = entityData.getColumns().getAll();
`EntityData.getColumns` 는 `new ColumnDatas` 로 한번 감싸서 반환하는데, 바로 `getAll` 을 통해 내부 변수를 가져오는 형태인 것 같아요. `getColumns` 에서 `new ColumnDatas` 로 감싼 이유가 있을까요?

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/metadata/Column.java
> +    }
value 를 가진 클래스를 만들어 반환하는 형태로 만들어주셨네요 👍

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/metadata/Column.java
> +        }
테스트코드를 제외하면 `Column` 은 정적 팩토리 메서드인 `from` 을 통해서만 생성되고 있어요.
`from` 은 파라미터로 `field` 를 받고 있는데, 멤버변수로 field 를 가지고 있으면 매번 `getClass().getDeclaredField(fieldName)` 를 할 필요 없지 않을까요?

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/metadata/ColumnMetadata.java
> +public class ColumnMetadata {
`ColumnDatas` 는 `ColumnData` 의 일급컬렉션으로 보이고, `ColumnMetadata` 는 `Column` 의 일급컬렉션으로 느껴지는데, 이름이 조금씩 다르네요. 어떤 기준으로 이름을 만들어주신건지 궁금해요 👀

2024-11-02 08:00 UTC, jongmin4943 commented on src/main/java/persistence/sql/metadata/EntityData.java
> +    private final List<ColumnData> columnDataList;
`ColumnDatas` 를 만들어 주셨는데 List<ColumnData> 로 쓰이는 곳들이 종종 보이네요. 어떤 기준으로 나눠서 사용하고 계신건지 궁금해요 👀

2024-11-02 08:00 UTC, jongmin4943 commented on src/test/java/persistence/DatabaseTest.java
> +public abstract class DatabaseTest {
통합테스트 환경을 재활용 하기 위해 분리해주셨네요 💯

2024-11-02 08:00 UTC, jongmin4943 commented on src/test/java/persistence/entity/DefaultRowMapperTest.java
> +        SimpleResultSet resultSet = createPersonResultSet(new Person(1L, "bob", 32, "test@email.com", 1));
`SimpleResultSet` 으로 꼼꼼하게 테스트 해주셨네요 👍

2024-11-02 08:00 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityManagerImplTest.java
> +        jdbcTemplate.execute(dmlQueryBuilder.buildInsertQuery(new Person("bob", 32, "test@email.com")));
각 테스트마다 `EntityManager` 를 위한 given 절이라기 보단, 테스트 시작 전 준비과정에 관한 부분이 조금씩 중복되고 있는 것 같아요. 해당 부분을 setup 같이 분리해보면 테스트 코드의 가독성이 올라가지 않을까요? :)

2024-11-04 09:09 UTC, sang5c reviewed
감사합니다 🙏

2024-11-04 09:09 UTC, sang5c commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
> +                + ";";
클래스로 만들자니 과한 것 같고, 텍스트 블록으로 만들자니 %s가 명확하지 않고 치환을 누락해도 컴파일 타임에 오류 발견이 어려워 계속 고민하다 이상태가 됐습니다 ㅎㅎ  

텍스트 블록으로 변경했습니다~

2024-11-04 09:09 UTC, sang5c commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
> +        List<ColumnData> columns = entityData.getColumns().getAll();
List로 보유하던걸 ColumnDatas로 변경했습니다.  
EntityData에서 ColumnData 내부의 데이터를 직접 접근하지 않는다는 기준으로 getColumns().getAll()을 유지했는데 이 부분은 어떻게 느껴지시나요?!

2024-11-04 09:09 UTC, sang5c commented on src/main/java/persistence/sql/metadata/Column.java
> +        }
말씀해주신대로 변경하는걸 시도해봤는데 두 가지 문제가 있습니다.

1. extractColumnValue() 호출 시점에 Column은 Entity의 class를 알 수 없습니다. 타입 안정성을 위해 entity를 기준으로 field를 가져오고, 여기에 값을 넣어주는 형태로 코드를 작성했습니다. 
이 문제를 해결하기 위해 관련 있는 Column, ColumnMetadata, EntityMetadata 등의 생성시점에 클래스 타입을 받아 타입 안정성을 높여주고 싶었는데, `class Column<T>` 형태로 만들려다가 산으로 가서 롤백을 했습니다... 😭
2. Column이 보유한 멤버는 Field에서 꺼낸 값입니다. Field를 갖는다면, 어떤 값을 멤버로 유지해야 하고(예: fieldName은 멤버로 유지해야 할지?) 어떤 값을 필요에 의해 꺼내 사용해야 할지 구분짓기 어렵습니다. 이후 개발에 혼선을 줄 것 같아서 최초 생성시에 field에서 값을 꺼내 필요한 데이터들을 Column이 보유한다는 기준으로 코드를 작성했습니다.

2024-11-04 09:09 UTC, sang5c commented on src/main/java/persistence/sql/metadata/ColumnMetadata.java
> +public class ColumnMetadata {
책임을 명확히 하기 위해(단순 메타데이터임을 나타내기 위해) 클래스명을 구분하여 적었습니다. 기가막힌 이름이 떠오르질 않네요..  
기존 클래스명을 ColumnDatas -> EntityData로, EntityData -> EntityWrapper로 변경해봤습니다.

2024-11-04 09:09 UTC, sang5c commented on src/main/java/persistence/sql/metadata/EntityData.java
> +    private final List<ColumnData> columnDataList;
직접 사용하지 않도록 변경했습니다~! 급한 작업의 흔적이라고 변명을...해봅니다

2024-11-04 09:09 UTC, sang5c commented on src/test/java/persistence/entity/EntityManagerImplTest.java
> +        jdbcTemplate.execute(dmlQueryBuilder.buildInsertQuery(new Person("bob", 32, "test@email.com")));
저는 given/when/then 패턴에서 given절에 속하는 코드가 setup으로 빠지는걸 우발적 중복이라고 느껴 지양하는 편인데요, 다른 분들한테 의견 들어본적이 없어서 지금 코드는 어떠신지 의견이 궁금합니다 ㅎㅎ

querybuilder, jdbcTemplate 생성같은, 직접적으로 테스트와 관련 없는 코드만 상위 클래스의 setup에서 수행하도록 숨겼습니다.
실제 어떤 데이터가 create, insert 되어있는지 모르는채로 select를 수행해서 성공하는 코드는 테스트 코드 규모가 커지면서 오히려 가독성이 떨어진다고 느꼈고 제 방식대로 한 번 작성해봤습니다.

2024-11-04 13:12 UTC, jongmin4943 approved these changes
안녕하세요 상오님!

4단계 미션 피드백 반영 잘 해주셨네요 👍
피드백에 대해 고민해주시고 받아주셔서 감사합니다 🙇 더 많은 이야기를 나누고 싶지만 미션의 진행을 위해 아쉽지만 여기서 마무리 하도록 하겠습니다. 만드신 부분들이 이후 미션들을 통해 어떤 모습으로 리팩토링 될지 궁금해지네요! 😃

미션 동안 많은 것을 얻어가셨으면 좋겠습니다.
남은 미션 완주 응원하겠습니다! 🚀

2024-11-04 13:12 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
>      }
피드백 반영해주셨네요 👍

2024-11-04 13:12 UTC, jongmin4943 commented on src/main/java/persistence/sql/dml/DmlQueryBuilder.java
> +        List<ColumnData> columns = entityWrapper.getColumns().getAll();
> List로 보유하던걸 ColumnDatas로 변경했습니다.
EntityData에서 ColumnData 내부의 데이터를 직접 접근하지 않는다는 기준으로 getColumns().getAll()을 유지했는데 이 부분은 어떻게 느껴지시나요?!

고민을 해주시고 반영해주셨네요 💯 
제 개인적인 의견으로는 아무래도 디미터의 법칙이 깨진 것 같아 마음 한편이 불편하다고 느껴지긴 해요 😢
지금 구조에서 어떤 식의 방향이 더 좋은지는 저도 고민이 드네요 🤔 

개인적으로 `EntityWrapper` 같은 경우 조금은 과한 추상화 일 수도 있다는 생각이 들어요. 실제 책임도 크지 않아 보이고, getter 를 통해 결국 내부 필드를 꺼내거나 위임만 해서 그렇게 느껴지는 것 같네요.

제 의견이니 상오님 생각대로 해보시며 추후 리팩토링을 해나가보시는 것도 좋을 것 같습니다 👍

2024-11-04 13:12 UTC, jongmin4943 commented on src/main/java/persistence/sql/metadata/Column.java
> +        }
1. 제가 드렸던 피드백은 이미 field 라는 정보를 가질 수 있는 클래스이다보니, `extractColumnValue` 호출 시점에는 이미 외부(`ColumnMetadata`)에서 어떤 Entity 인지 알고 있다는 점을 통해 어떤 `Column` 을 지정하고 움직이는지 알 수 있지 않을까 해서 드렸던 피드백이었습니다. 😃 
또한, 필요하다면 처음 생성 시 주입을 하거나, `field.getDeclaringClass` 를 이용하면 entity class 를 알 수 있지 않을까 생각이 들기도 하네요. 작은 객체가 큰 객체를 알고 있게 되는 단점으로 마음에 들지 않긴 하네요 🤔

2. 좋은 생각이라 생각합니다. 저도 고민하는 포인트이긴 해요 :) 고민 후 내린 결정이시라면 OK 입니다 👍

2024-11-04 13:12 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityManagerImplTest.java
> +        Person person = entityManager.find(Person.class, 1L);
> 저는 given/when/then 패턴에서 given절에 속하는 코드가 setup으로 빠지는걸 우발적 중복이라고 느껴 지양하는 편인데요, 다른 분들한테 의견 들어본적이 없어서 지금 코드는 어떠신지 의견이 궁금합니다 ㅎㅎ
querybuilder, jdbcTemplate 생성같은, 직접적으로 테스트와 관련 없는 코드만 상위 클래스의 setup에서 수행하도록 숨겼습니다.
실제 어떤 데이터가 create, insert 되어있는지 모르는채로 select를 수행해서 성공하는 코드는 테스트 코드 규모가 커지면서 오히려 가독성이 떨어진다고 느꼈고 제 방식대로 한 번 작성해봤습니다.

1. DdlQueryBuilder 를 생성한다
2. DmlQueryBuilder 를 생성한다
3. JdbcTemplate 을 만든다
4. Person 을 이용해 createQuery 를 만들어 jdbc 로 실행한다.
5. Person entity 를 이용해 insertQuery 를 만들어 jdbc 로 실행한다.
6. 특정 메서드를 테스트를 한다
7. 검증한다

여기서 `EntityManager` 의 특정 메서드가 잘 작동하는지 검증을 하는데, 기존에 만들어주셨던 부분은 알아야하는 컨텍스트가 너무 많다고 느껴졌어요. 그렇다보니 정말 테스트 하려는 것에 집중하지 못하는 느낌을 받았습니다.

given 절에서 setup 으로 올라가는 건 각자만의 기준이 있을 것 같아요. 지금 해주신대로 메서드로 빼기만 해도 충분히 좋다고 생각합니다! 👍  

1. given 절이 현재 테스트하려는 메서드와 얼마나 연관이 있는가
2. 현재 테스트가 기능 테스트에 집중했는가
3. 테스트 코드를 읽고 파악하기 편한가

로 생각해보고 있습니다.  setup 으로 올라감으로써 테스트 코드를 읽고 파악하기 힘들어지는 경우도 잘 고려를 해봐야하지 않을까요? :)

2024-11-04 13:12 UTC, merged