[Step2] QueryBuilder DDL
next-step/jpa-query-builder pull request #62
Opened 2023-10-18 08:06 UTC by hhhhhwi

안녕하세요! 
[Step2] QueryBuilder DDL PR 리뷰 요청 드립니다.

쿼리를 이루고 있는 요소들을 각각 나눠서 했는데.. 제대로 역할에 맞게 분리를 했는 지 잘 모르겠네요 😕 
고민에 고민을 거듭한 끝에.. 벌써 수요일이 되어서 일단 PR 리뷰부터 요청 드립니다.

1단계에 대한 리뷰에 대한 피드백도 반영했습니다!
이번에도 하나하나 잘 개선해나가겠습니다😄

2023-10-18 15:50 UTC, jwee0330 requested changes
안녕하세요 휘연님
말씀드린 피드백도 잘 반영해 주시고 step2 미션 구현도 잘 해주셨네요!
세세하게 커밋도 나눠주시고 코드도 워낙 깔끔해서 리뷰 하기가 정말 좋았습니다
특히 Column 과 Constraint 객체를 생성해 주신 부분이 정말 좋았어요 👍 
조금 더 책임을 부여해도 괜찮지 않을까? 하는 생각이 들어 몇 가지 코멘트 드렸습니다
고민해 보시고 수정하신 후 다시 PR 요청 부탁드립니다 🙇🏻‍♂️
궁금하신 부분은 dm 보내주세요 :)

2023-10-18 15:50 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +                .collect(Collectors.joining(", ")).toString();
```suggestion
                .collect(Collectors.joining(", "));
```
필요없는 부분은 제거해주세요

2023-10-18 15:50 UTC, jwee0330 commented on src/test/java/persistence/study/ReflectionTest.java
> +        );
피드백 반영 좋습니다 👍 
assertAll 과 여러 줄의 assert 코드의 차이점에 대해 고민해 보셨을 것 같아요 :)

2023-10-18 18:02 UTC, hhhhhwi commented on src/main/java/persistence/sql/ddl/ColumnBuilder.java
> +        ConstraintBuilder constraintBuilder = new ConstraintBuilder();
무심코 메소드 안에 생성자를 넣었네요; 
아래 제안 주신대로 Constraint 객체에 ConstraintBuilder역할을 부여하므로서 해당 생성자가 필요가 없어졌습니다 ㅎㅎ

2023-10-18 18:15 UTC, hhhhhwi commented on src/main/java/persistence/sql/ddl/QueryBuilder.java
> +abstract class QueryBuilder {
링크 첨부 감사합니다! 

해당 상속 구조로 개발한 목적은 코드의 재활용도 있지만, QueryBuilder의 역할을 표준화하기 위함도 있었기 때문입니다..!
그래서 유효성 검사 등의 성격이 다른 메소드는 조합을 이용하여 수정하고 QueryBuilder를 인터페이스로 구현해봤습니다..!

2023-10-18 18:18 UTC, hhhhhwi commented on src/main/java/persistence/sql/ddl/ColumnBuilder.java
> +public class ColumnBuilder {
구현을 하면서 Column의 리스트 컬렉션을 ColumnBuilder에서 상태 변경한다는 점이 가장 걸렸었는데...
이런 방법이 있었군여..! 😃

2023-10-19 16:41 UTC, jwee0330 approved these changes
안녕하세요 휘연님
피드백 반영 하시느라 고생 많으셨습니다 🙇🏻‍♂️
몇가지 개선 포인트들 코멘트 드렸습니다
다음 단계 시작 하실때 고민해 보시고 반영해 주셨으면 좋겠습니다:)
요구사항은 전부 만족해서 머지하도록 하겠습니다 👍

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/ColumnBuilder.java
> +                .append(column.getConstraint().buildNullable())
아래 내용을 확인해 보시면 도움이 되실것 같아요:)

객체지향 생활체조 원칙 4. 한줄에 점 하나만 찍는다
https://limdingdong.tistory.com/10

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/Constraint.java
> +    private final static String NOT_NULL_CONSTRAINT = " NOT NULL";
google java style guide 에서 `private static final` 순의 컨밴션을 제시하고 있어요
이번 기회에 한번 적용해 보시죠!

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/Constraint.java
>      private boolean isPrimaryKey;
final 선언하여 불변객체로 만들 수 있을것 같아요

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/Constraint.java
> +        }
아래 링크를 참고해보시고 다음단계에서는 swich 문 없이 구현해 보셨으면 좋겠습니다🙏🏻

객체지향 생활 체조원칙 2. else 예약어를 사용하지 않는다
https://limdingdong.tistory.com/8

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +                new ColumnBuilder((convertClassToColumnList(clazz))).buildColumnList() +
ColumnBuilder 도 CreateQueryBuilder 에 주입하도록 변경해 보는건 어떨까요?

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
>      private List<Column> convertClassToColumnList(Class<?> clazz) {
ColumnBuilder 의 책임에 더 가깝다고 생각이 드네요
ColumnBuilder 의 생성자에 Class 를 받아서 일급컬랙션을 생성해 보는건 어떨까요?

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/DropQueryBuilder.java
> +    private final static String DROP_TABLE_COMMAND = "DROP TABLE %s;";
`private static final` 컨밴션에 맞춰볼까요?

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/ColumnBuilder.java
> +    public String buildColumnList() {
이제 일급컬렉션으로 분리되었으니 해당 메서드도 테스트 코드를 통해 검증을 해볼까요?

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/ColumnBuilder.java
> +    private List<Column> columns;
일급컬랙션 생성 👍

2023-10-19 16:41 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +        return format(CREATE_TABLE_COMMAND, new Table(clazz).getName()) +
Table 도 주입 받도록 하면 더욱 좋을것 같아요 :)

2023-10-19 16:41 UTC, merged