2단계 - QueryBuilder DDL 리뷰요청
next-step/jpa-query-builder pull request #63
Opened 2023-10-18 12:32 UTC by profoundsea25

안녕하세요!
생각보다 오래 걸렸네요 ㅠㅠ

TDD를 하겠다는 큰 마음을 품고 했는데 제일 중요한 클래스 2개 뺴고는 못 했네요 ㅜ
설계가 정말 어려웠습니다.
DB가 바뀌면 SQL도 바뀌는데 그런건 어떻게 대처하지?
필드에 따라서 속성 값을 명시해주는 건 어떻게 하지?
등등...

아무튼 잘 부탁드립니다!

2023-10-18 16:56 UTC, leeyohan93 requested changes
안녕하세요 해준님 😄 
이전 피드백도 잘 적용해주시고 이번 단계도 너무 잘 구현해주셨습니다!
코드에서 얼마나 많은 고민들을 하셨을 지 보여서 인상 깊었습니다 💯 💯 
다음 단계로 넘어가기 이전에 고민해보면 좋을 부분들에 대해 몇몇 코멘트 남겨두었습니다.
확인해보시고 고민이 되시는 부분 있다면 편하게 코멘트 남겨주세요 😄 
감사합니다 🙏

2023-10-18 16:56 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/dialect/Dialect.java
> +public abstract class Dialect {
각 DB 마다 각각 구현할 수 있도록 추상화를 잘 해주셨네요 👍 
추가적으로 추상클래스를 사용하게되어 자식 클래스가 부모 클래스의 구조를 알아야하는 단점이 있는 것 같습니다.
추상클래스 대신 인터페이스를 사용해보는건 어떨까요?

2023-10-18 16:56 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2Dialect.java
> +    public String getColumnPartInCreateQuery(EntityColumn entityColumn) {
Dialect에서 타입을 매핑하고 쿼리를 만드는 두 가지 책임을 수행하고 있는 것 같아요.
만들어주신 이름에 어울리도록 Dialect에서는 H2 타입에 대한 처리를 담당하고 쿼리를 만드는 책임을 적절한 객체에 분리해보면 어떨까요? :)

2023-10-18 16:56 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2Dialect.java
> +        dropQuery.append("if exists ");
굉장히 여러 케이스도 함께 고민해보신 흔적이 보이네요 👍 💯

2023-10-18 16:56 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/entity/EntityColumn.java
> +    }
사용되지 않는 코드는 제거해주셔도 좋을 것 같아요 :)
구현해주신 다른 isXXX() 메서드들 과는 성격이 조금 달라보여서 활용 되기는 어렵지 않을까 생각이 들기도 하네요! 🤔

2023-10-18 16:56 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/entity/EntityColumns.java
> +public class EntityColumns {
일급 컬렉션 활용 👍 
객체 지향에 익숙해보시고 경험해보신 것 같네요 :) 
다만 아직 해당 일급 컬렉션은 적절한 책임을 수행하고 있지는 않은 것 같습니다. 고민해보시면 좋을 포인트 같아요 😄

2023-10-18 16:56 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/entity/EntityName.java
> +    }
작성해주신 EntityName은 유틸 클래스에 가까워보이네요 🤔 
유틸 클래스는 편리하다는 장점도 있지만 단점으로 주요 로직이 분산 될 수 있습니다.
별도의 유틸 클래스 대신 적절한 객체에 책임을 할당해주도록 변경해보는건 어떨까요?

클래스를 작게 분리하는 것은 정말 중요하지만, 적절한 책임에의해 만들어져야하며 항상 오버엔지니어링은 경계해야합니다 :)

2023-10-18 16:56 UTC, leeyohan93 commented on src/test/java/persistence/sql/ddl/CreateQueryBuilderTest.java
> +class CreateQueryBuilderTest {
객체들을 너무 잘 분리해주셨는데 단위테스트가 없어서 아쉽습니다 😢
TDD로 진행하시기에 어려움이 있으시겠지만, 단위 테스트 또한 도움이 많이 되니 함께 작성해주시면 좋을 것 같습니다 👍

2023-10-19 10:26 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/dialect/Dialect.java
> +public abstract class Dialect {
추상 클래스 상속 시, 모든 세부 사항들이 상속 클래스에 영향을 주는 부분을 고려해서 interface로 변경했습니다.

2023-10-19 10:27 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2ColumnType.java
> +    STRING(String.class, "varchar", H2ColumnTypeProperties::getVarcharLength),
의도는 관련 속성이 있을 경우 추가적인 메서드 호출이 필요하다를 Enum을 보는 것만으로도 알수 있게 하고 싶었는데,
마땅한 방법이 떠오르지 않아 null로 처리했었던 내용입니다.

properties를 아예 삭제하고, 필요한 부분은 따로 H2ColumnTypeProperties에서 메서드를 처리하도록 수정했습니다.

2023-10-19 10:29 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/entity/EntityColumn.java
> +    }
오 인텔리제이에서 회색 글씨로 안 보여서 몰랐네요;; 활용이 어려운 것 같아 삭제했습니다!

2023-10-19 10:29 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2Dialect.java
> +        dropQuery.append("if exists ");
감사합니다 ㅎㅎ...

2023-10-19 10:30 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/entity/EntityColumns.java
> +public class EntityColumns {
아직까지는 컬림 List 중에 Id 컬럼만 따로 식별한다.. 만 하고 있네요.
어떻게 활용할지는 좀 더 고민해보겠습니다.

2023-10-19 10:41 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/entity/EntityName.java
> +    }
기존에 존재하는 객체에 로직을 옮기는 것으로 이해하면 될까요?
일단 테이블 이름을 추출하는 객체는 필요할 것 같아서 만들었는데 딱히 필드를 가질 필요가 없어서 유틸 클래스 비스무리한 무언가가 되었군요.. 
일단 static 모두 제거하고 entityClass를 필드로 가지는 클래스로 변경했습니다!

2023-10-19 11:13 UTC, profoundsea25 commented
@leeyohan93 님! 주신 피드백 반영해보았습니다.
일단 CreateQueryBuilder에 있던 로직들을 H2CreateQueryBuilder로 옮기고, Dialect 인터페이스화, Query 인터페이스 추가 등 많은 변경점이 있었네요;;
쿼리를 구현하는 구체적인 로직들을 Query 인터페이스를 구현하는 클래스 (H2CreateQuery, H2DropQuery)로 옮겼습니다.

피드백 요청 드립니다!

2023-10-19 14:14 UTC, profoundsea25 commented on src/test/java/persistence/sql/ddl/CreateQueryBuilderTest.java
> +class CreateQueryBuilderTest {
단위테스트가 필요한 객체들에 테스트코드 추가하였습니다

2023-10-19 16:57 UTC, leeyohan93 approved these changes
안녕하세요 해준님 😄 
피드백 반영도 잘 해주시고 이번 PR 에서도 많은 고민을 하고 노력하신 점이 보여서 좋았습니다 💯 
고생 많으셨고 또 궁금한 점이 있으시다면 코멘트나 남겨주세요 😄 
다음 단계를 진행하기 전에 고민해보시면 좋을 몇몇 코멘트도 남겨두었으니 확인 부탁드립니다.
이번 단계는 여기서 머지하도록 하겠습니다. 다음 단계도 화이팅입니다. 🔥

2023-10-19 16:57 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +    public CreateQueryBuilder(Dialect dialect, Class<?> objectClass) {
QueryBuilder를 클래스마다 생성하는 대신, 싱글톤으로 사용해보는건 어떨까요?
매번 빌더를 생성하는 비용을 줄일 수 있을 것 같아요 :)

2023-10-19 16:57 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/entity/EntityData.java
> +    private final Class<?> entityClass;
사용되지 않는 변수는 지워주셔도 좋을 것 같아요 :)

2023-10-19 16:57 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/dialect/Dialect.java
> +}
이전에 드린 피드백에서 이야기드렸던 것과 동일하게 아직 Dialect 은 두가지 책임을 가지고 있는 것 같습니다.
- 자바 타입과 데이터 베이스 타입을 매핑
- 쿼리를 생성

지금 구현된 책임 만으로 생각해보면 Dialect(방언) 보다는 QueryBuilder 라고 생각이 되는 것 같습니다!
클래스 명 또한 어떠한 책임을 가지고 있느냐에 따라 달라질 수 있기 때문에 고민해보시면 좋은 포인트가 될 것 같습니다 😄

2023-10-19 16:57 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2CreateQuery.java
> +        List<EntityColumn> entityColumns = entityData.getEntityColumns().getEntityColumns();
EntityData 클래스 내부에서 쿼리를 만드는 일을 하지 않도록 구현해주시니 getter가 많이 사용되고 있네요 😢 
저 또한 EntityData가 쿼리와 관련되지 않고 온전히 쓰이도록 구현해주신 것도 괜찮은 방향이라고 생각합니다 👍 
이 부분에서는 트레이드 오프가 있는 부분이라 생각되어 해준님도 한번 고민해보시면 좋을 것 같아 코멘트 남깁니다 😄

2023-10-19 16:57 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2Query.java
> +public interface H2Query extends Query {
상수를 모아두기위해 인터페이스를 사용하는건 조금 고민이 되는 부분이네요! 🤔 
인터페이스 대신 상수를 모아두는 별도의 클래스를 만드시는 것도 괜찮을 것 같습니다 :)

2023-10-19 16:57 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/entity/EntityName.java
> +public class EntityName {
> 기존에 존재하는 객체에 로직을 옮기는 것으로 이해하면 될까요?
일단 테이블 이름을 추출하는 객체는 필요할 것 같아서 만들었는데 딱히 필드를 가질 필요가 없어서 유틸 클래스 비스무리한 무언가가 되었군요..
일단 static 모두 제거하고 entityClass를 필드로 가지는 클래스로 변경했습니다!

기존에 객체에 로직을 옮기는 방법이나, 구현해주신 방법 모두 괜찮은 방법이라고 생각합니다 :)

2023-10-19 16:57 UTC, merged

2023-10-20 05:46 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +    public CreateQueryBuilder(Dialect dialect, Class<?> objectClass) {
각각의 QueryBuilder들이 런타임에서 객체 생성이 한 번만 되도록 하면 된다는 의미인가요?
엔티티 클래스에 대한 정보는 동적으로 받아서 처리하도록 만들어보겠습니다

2023-10-20 05:47 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/entity/EntityData.java
> +    private final Class<?> entityClass;
앗; 놓쳤군요! 감사합니다

2023-10-20 05:48 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/dialect/Dialect.java
> +}
Dialect를 생각해보니 쿼리를 만들고 있어서 뭔가 이름을 잘못 지은 것 같아요. 이름 변경했습니다.
자바 타입과 데이터 베이스 타입을 매핑하는 클래스는 따로 있는데, 이걸 쿼리를 만드는 시점에 호출해야만 해서, 어떻게 분리할지 좀 더 고민해보겠습니다.

2023-10-20 05:49 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2CreateQuery.java
> +        List<EntityColumn> entityColumns = entityData.getEntityColumns().getEntityColumns();
EntityData에서는 진짜 정보만 가지고 있자... 라고 생각을 하고, 쿼리를 만드는 부분에서 추출하도록 만들었습니다.
그러다 보니 getter가 노출되더라구요 ㅠ
고민해보겠습니다!

2023-10-20 05:51 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/dialect/h2/H2Query.java
> +public interface H2Query extends Query {
Enum이나 static 클래스로 따로 빼보도록 하겠습니다!

2023-10-20 07:30 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +    public CreateQueryBuilder(Dialect dialect, Class<?> objectClass) {
네 맞습니다.
저희가 실무에서 바라보면 Dialect 과 같은 `데이터베이스`는 동적으로 자주 바뀌지 않고, 쿼리 생성에 대한 `클래스 타입`은 동적으로 굉장히 많이 바뀌게됩니다.

쿼리 빌더 생성 시 데이터베이스를 설정하고, 쿼리 생성 시에 동적으로 클래스 타입을 받도록하면 매번 쿼리 빌더를 만드는 것보다 좋은 성능과 구조를 함께 가져갈 수 있을 것 같습니다 😄