[step3] - QueryBuilder DML 작성하기 & 구조 리팩토링
next-step/jpa-query-builder pull request #67
Opened 2023-10-19 02:00 UTC by beng9re

안녕하세요!  정완님

DM으로 말씀드렸던것처럼 step3 진행하기전에 나눴던 내용을 기반으로 리팩토링 후 요구사항 1번을 해결했는데요

QueryGenerator - > QueryBuilder->  Model 의 흐름으로 작성을 진행을 하였고 
하다 보니 구조적으로 많은 변경이 이루어져서 한번 검토차 리뷰를 올리게 되었습니다.

잘 부탁드립니다! 🙇‍♂️

2023-10-19 10:06 UTC, ghojeong requested changes
김병희님!

아직 요구사항 1단계만을 구현하셨기에, 지난번 피드백의 반영사항과 패키지 구조에 대해서만 코드리뷰를 남겼습니다.
굉장히 많은 리팩토링이 이루어졌는데 저는 지금의 구조에 충분히 만족합니다!
 나머지 findAll, findById, delete 요구사항도 구현 화이팅입니다 🔥

2023-10-19 10:06 UTC, ghojeong commented on src/main/java/persistence/meta/EntityMeta.java
> +    private final EntityColumns entityColumns;
meta 라는 패키지를 따로 만들고 EntityMeta 를 따로 선언해주신 점 매우 좋습니다! 👍 
앞으로 meta 패키지 안에 들어가는 객체들은 ddl, dml 뿐만 아니라,
EntityManager 나 영속성 컨텍스트에 이르기까지도 계속 활용될 객체들이라 생각하고 리뷰드리겠습니다.

2023-10-19 10:06 UTC, ghojeong commented on src/test/java/persistence/fake/FakeDirect.java
> +public class FakeDirect extends H2Dialect {
이곳은 아직 Direct 오타가 고쳐지지 않았군요 😜

2023-10-19 10:06 UTC, ghojeong requested changes
김병희님!

아직 요구사항 1단계만을 구현하셨기에, 지난번 피드백의 반영사항과 패키지 구조에 대해서만 코드리뷰를 남겼습니다.
굉장히 많은 리팩토링이 이루어졌는데 저는 지금의 구조에 충분히 만족합니다!
 나머지 findAll, findById, delete 요구사항도 구현 화이팅입니다 🔥

2023-10-19 10:17 UTC, beng9re commented on src/main/java/persistence/sql/QueryGenerator.java
> +    private final Dialect dialect;
사실 이부분 작성하다보니 그런구조가 되어버렸는데 DML 작업을 미리 하면서  있는데 팩토리 형태로 구조 변경이이 진행될꺼 같습니다.

2023-10-19 10:22 UTC, beng9re commented on src/main/java/persistence/vender/dialect/H2Dialect.java
> +        return String.format("varchar(%d)", length);
처음부터 DB Vendor 별로 구현체가 달라질꺼 같아서 확실하게 찢어 보았는데 한편으로는 엄청 거리감 있는 패키지 구조가 되었네요. 고려해보겠습니다.

2023-10-19 10:24 UTC, beng9re commented on src/test/java/persistence/fake/FakeDirect.java
> +public class FakeDirect extends H2Dialect {
😇 혼란이 왔었나봐요

2023-10-20 17:18 UTC, beng9re commented
정완님!

findAll, findById, delete 요구사항까지 구현 완료 하였습니다.
리뷰 부탁드리겠습니다!

2023-10-21 00:40 UTC, ghojeong commented on src/test/java/persistence/fake/FakeDirect.java
> +public class FakeDirect extends H2Dialect {
흑흑 오타는 수정해주시지 않는 건가요?

2023-10-21 00:56 UTC, beng9re commented on src/test/java/persistence/fake/FakeDirect.java
> +public class FakeDirect extends H2Dialect {
ㅠㅠ. 왜 이러죠.. 수정했습니다!

2023-10-21 02:06 UTC, ghojeong approved these changes
김병희 님!

테스트를 정성스럽게 작성해주셔서, 테스트 쪽으로는 칭찬 말고는 드릴 말씀이 없네요. 👍 
사소한 오타와 함께 다음주 미션 진행에 도움이 되었으면 하는 생각할 거리들을 몇가지 남겨보았습니다.
많은 고민을 해주신 만큼, 오늘 EntityManager 수업이 굉장히 재미있으시리라 생각됩니다.
벌써 마지막 Step 이군요. 화이팅입니다! 🔥

2023-10-21 02:06 UTC, ghojeong commented on src/main/java/repository/DDLRepository.java
> +    private final JdbcTemplate jdbcTemplate;
어플리케이션 레벨에서 프레임워크와 상호작용하는 부분이 될 수 있도록
벌써 부터 Repository 를 만들어주신 점 대단하십니다! 👍 

미션 진행만 한 코드를 보면, 그래서 이 코드를 앱 개발을 할 때 어떻게 써야하지
하고 실제 코드를 다 읽어봐야하는데,
병희님은 repository 가 존재해서, 아 이걸 import 해서 쓰면 되겠구나 확 느껴지네요.

미션을 넘어선 디테일 신경써주셔서 멋집니다. 💯

2023-10-21 02:06 UTC, ghojeong commented on src/test/java/repository/RepositoryTest.java
> +                        dynamicTest("존재하지 않으면 예외가 발생한다.", () -> {
실제로 DB 에 쿼리를 날려서 Repository 레벨에서의 테스트 까지 작성해주셔서 정말 멋집니다.
이 정도면 동료 개발자 입장에서, 믿고 마음편하게 사용할 것 같습니다. 👍

2023-10-21 02:06 UTC, merged

2023-10-21 05:54 UTC, beng9re commented on src/main/java/jdbc/EntitySingleMapper.java
> +    }
아 역시 고민이 많았는데 null 보다는 옵셔널이 좋아보이네요

2023-10-21 05:55 UTC, beng9re commented on src/main/java/jdbc/AbstractRowsMapper.java
> +    private Field getFiled(Class<T> tClass, EntityColumn entityColumn) {
아무래도 플러그인을 찾아봐야 되겠어요! 맨날 한다하고 놓치는 부분이 많네요

2023-10-21 07:20 UTC, beng9re commented on src/main/java/jdbc/AbstractRowsMapper.java
> +    }
Step4 엔티티 매니저에서 심도있게 구현해봐야겠네요 🔥

2023-10-21 07:21 UTC, ghojeong commented on src/main/java/jdbc/AbstractRowsMapper.java
> +    }
Step4 에서 절대 심도있게 구현하지 마시고,
가볍게 구현하신 후 다음 주차로 넘어가주세요.
어차피 다음주차에서 할게 많습니다.

2023-10-21 07:25 UTC, beng9re commented on src/main/java/persistence/sql/dml/InsertQueryBuilder.java
> +    }
고민 한번 해보겠습니다!

2023-10-21 07:28 UTC, beng9re commented on src/test/java/jdbc/EntityRowMapperTest.java
> +}
EntityRowsMapper에 대한 테스트를 만들어볼까하다가 통합테스트에 이관하였습니다