[1주차 - Step 4] Simple Entity Object PR 입니다.
next-step/jpa-query-builder pull request #69
Opened 2023-10-19 15:26 UTC by jongmin4943

일단 Step4 시작 전에 페이징쿼리 추가하는걸 해봤습니다. 쿼리빌더를 추상화 하라고 하셨는데 그쪽 방향으로는 뭔가 생각이 잘 안되어서 일단 방언으로 처리로 해보았습니다.

그리고 진행하다가 이상한길로 한번 빠졌다가 돌아왔습니다. `DB 타입을 시작할때 정하면 바꿀수 없겠지` 라는 생각에 전역으로 관리를 생각했었습니다. 그런데 만들고 나니 테스트를 진행하기가 힘들고, 한번 더 생각해보니 여러개의 Database 를 연결 할수도 있겠다는 생각에 객체 생성으로 변경하였습니다.

이제 뭔가 상상력의 한계점이 온 느낌입니다. 계속 리팩토링 지점을 찾아보다가 리뷰를 받아보면 좋지않을까 라는 생각에 PR 보내봅니다.

2023-10-20 03:31 UTC, ghojeong requested changes
윤종민님!

마지막 Step 도 매우 훌륭하게 작업해주셨습니다!
특히 DB 관련해서 추상화해주신점 엄청 멋집니다 👍 
동료 개발자가 넘겨받는다 하더라도 테스트의 유지보수를 기꺼이할만큼
멋지고 쉬운 구조가 된 것 같습니다.

사소하게 오타를 발견한 부분과, 궁금증이 생긴 부분에 대한 질문을 남겨보았습니다.
답변 주시고 미션을 마무리하고 싶으실 때 편하게 요쳥주세요!

2023-10-20 03:31 UTC, ghojeong commented on src/test/java/persistence/ApplicationTest.java
> +        });
이런 느낌의 테스트는 Getter 가 더 직관적이지 않을까 취향을 이야기해봅니다.
getName 같은 경우는 언젠가 쓰일것 만 같은 메서드인데,
isName 은 테스트만을 위한 메서드라는 느낌이 들어서요.
참고로 이건 정말 취향 차이이므로 반영하지 않아도 괜찮습니다.

2023-10-20 03:31 UTC, ghojeong commented on src/test/java/database/MockDatabaseServer.java
> +public class MockDatabaseServer implements DatabaseServer {
테스트를 위한 Mock 객체 만들어주신점 멋집니다. 👍 
이미 여러 테스트 방법론에 익숙하시군요.

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/dialect/Dialect.java
> +}
paging 과 타입에 대해서 Dialect 를 통해 추상화 해주신 점 좋습니다. 👍 
저도 딱 이 정도의 추상화를 바랬습니다.

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/dialect/PagingStrategy.java
> +    }
캬아 예외처리까지 아주 꼼꼼하시군요 👍

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/dialect/H2Dialect.java
> +public class H2Dialect implements Dialect {
OracleDialect 와 H2Dialect 가 같은 패키지에 존재하는데,
`dialect.h2` 와 `dialect.oracle` 로 패키지 계층을 세분화하면 어떨지 제안해봅니다.
나중에 동료 개발자 입장에서 `dialect.mysql` 을 만들려고 할 때,
어디까지 코드를 복붙해야하고, 어떤 코드를 import 해서 재사용하면 되는지 더 명확해질 것 같아서요.

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/dialect/OracleDialect.java
> +    }
저는 지금도 충분히 멋진것 같은데,
임시라는 주석을 남기신 의도가 있으신가요?

2023-10-20 03:31 UTC, ghojeong commented on src/test/java/persistence/dialect/PersistenceEnvironmentStrategyTest.java
> +    }
OracleDialect 전략을 선택했지만, H2Dialect 의 클래스라니 매우 기묘하군요... 😭 
테스트도 실패하는 것 같은데 코드 리뷰를 신청하기전 테스트를 미리 돌려보는 습관을 가지면 좋을 것 같습니다.

2023-10-20 03:31 UTC, ghojeong commented on src/test/java/persistence/dialect/DefaultPagingStrategyTest.java
> +    }
키야 추가 요구사항이었지만 꼼꼼한 테스트 작성해주셔서 멋집니다. 👍

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/entity/EntityManager.java
> +}
EntityManager 를 인터페이스로 추상화해주신 점 멋집니다. 👍 
지금은 SimpleEntityManager 만이 존재하는데, 무엇을 기준으로 다른 EntityManager 가 필요하게 될지 의도가 궁금해서 여쭈어봅니다.
가령 Dialect 인터페이스는 DB 마다 다른 구현체가 필요하다는 명확한 기준이 있지요.
EntityManager 도 종민이 생각해두신 기준이 있을지 궁금해서 여쭈어보았습니다.

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +        }
이번주 토요일날 수업때 다룰 내용이었는데,
EntityManager 에서 connection 관리를 하도록 역할을 배정하다니 놀랍군요! 👍 

기왕 close 를 지원하게 된거,
EntityManager 도 try-with-resources 를 활용할 수 있도록 하면 어떨까 제안해봅니다.

2023-10-20 03:31 UTC, ghojeong commented on src/main/java/persistence/core/PersistenceEnvironmentStrategy.java
> +}
PersistenceEnvironmentStrategy 도 추상화해주셨군요 👍 
DefaultPersistenceEnvironmentStrategy 외에 어떤 구현체가 존재할 수 있을 지 궁금해서,
질문을 남겨봅니다.

2023-10-20 10:35 UTC, jongmin4943 commented on src/test/java/persistence/ApplicationTest.java
> +        });
사실 처음에 Getter 를 만들었다가 다시 바꾼거긴한데.. 사실 이 부분을 여쭤보고 싶었습니다. 저도 Getter 만드는걸 선호하는지라.. 바꾸겠습니다!

2023-10-20 10:46 UTC, jongmin4943 commented on src/main/java/persistence/dialect/H2Dialect.java
> +public class H2Dialect implements Dialect {
적용해보겠습니다

2023-10-20 10:48 UTC, jongmin4943 commented on src/main/java/persistence/dialect/OracleDialect.java
> +    }
`OracleColumnTypeMapper` 를 만들긴했는데 그냥 `H2ColumnTypeMapper` 를 그대로 복사해서 붙여넣었거덩요.. 그래서 임시 표시를 그 당시 잠시 해뒀었는데 깜빡했네요. 지우겠습니다!

2023-10-20 10:51 UTC, jongmin4943 commented on src/test/java/persistence/dialect/PersistenceEnvironmentStrategyTest.java
> +    }
어허.. 이상하네요. 돌리고 넘어가는거 확인도 한 테스트이고, 심심하면 전체 테스트를 돌리면서 초록불을 보며 위안을 삼는 버릇이 있는데.. 지금 돌려보니 이상한 버그가 나고 있네요.

![image](https://github.com/next-step/jpa-query-builder/assets/77711322/510d4c91-9ea5-4e88-90db-271034230267)

전체 테스트에서는 해당 테스트 메서드를 아에 실행도 안시키고 있었어요. 해결해보겠습니다

2023-10-20 11:03 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityManager.java
> +}
다른것들을 만들때는 인터페이스를 딱히 먼저 두지는 않았습니다. 왜냐하면 시스템 내부적으로 이용되는것들이라 생각했기 때문입니다.

하지만 EntityManager 는 실제 클라이언트와 소통하는 부분이라는 생각이 들었습니다. 그래서 EntityManager 인터페이스와 SimpleEntityManager 라는 구현체를 만들어 뒀습니다. 이렇게 하면 사용하는쪽에서는 인터페이스만 바라보니 제가 EntityManager 를 막 변경해도 사용하는 클라이언트 쪽에서의 변경을 최소화 할 수 있지 않을까 생각했습니다.

또한 지금은 SimpleEntityManager 는 JdbcTemplate 을 사용해 DB 에 접근하고 있지만, 다른 방식으로 DB 에 접근할때는 다른 구현체를 만들어 사용하게 하는 방법도 있지 않을까? 라는 생각도 했었습니다.

2023-10-20 11:05 UTC, jongmin4943 commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +        }
안그래도 try-with-resources 를 활용하기 위해 AutoCloseableTemplate 이라는 클래스를 만들어 시도를 해보았는데 EntityManager 를 생성할때 이미 connection 을 가져온 상태이고 사용자가 find 나 persist 같은 것을 여러번 호출 할 수 있기에 언제 어디를 AutoCloseableTemplate 로 감싸야 할지 알 수가 없어서 사용할 수 없었습니다.

혹시 더 좋은 방법이 있을까요?

2023-10-20 11:07 UTC, jongmin4943 commented on src/main/java/persistence/core/PersistenceEnvironmentStrategy.java
> +}
이 부분은 이상한길로 한번 빠졌다가 나온 잔재네요.. `PersistenceEnvironment` 로 다시 옮겨도 괜찮아 보이네요.

2023-10-20 11:16 UTC, jongmin4943 commented on src/test/java/persistence/dialect/PersistenceEnvironmentStrategyTest.java
> +    }
음.. 이런적은 처음인데
![image](https://github.com/next-step/jpa-query-builder/assets/77711322/47602d6a-d523-4bb2-aab6-d143b4ba91fa)
Gradle 의 `Build and run using` 을 `Intelij IDEA` 로 바꾸니 정상 작동 하네요.
보통 `Build and run using` 은 Gradle 로 두는 편인데.. 왜 그러는진 잘 모르겠습니다

2023-10-20 11:41 UTC, ghojeong commented on src/test/java/persistence/dialect/PersistenceEnvironmentStrategyTest.java
> +    }
IntelliJ 의 캐싱 혹은 설정과, gradle 의 설정 혹은 캐싱이 충돌하는 경우가 저도 종종 발생하더라고요.
IntelliJ 로 개발할 때는 세팅을 위처럼 해주시는게 바람직한것 같습니다.

2023-10-20 11:50 UTC, ghojeong commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +        }
흠... 무심코 다다음주 수업내용을 스포해버렸는데,
종민님이 말씀하신 문제를 해결하기 위해서는 EntityManager 를 넘어 영속성 컨텍스트에 대한 이해가 필요합니다.
Hibernate 구현체에서는 [Session](https://github.com/hibernate/hibernate-orm/blob/624040c9a3626b1b28d99d50c662a84b81fffbdc/hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java#L233) 이라는 개념을 통해 DB 와의 connection 을 맺고 끊는 문제를 해결하고 있습니다.

문제는 Hibernate 의 Session 이 제 기준으로는 그리 깔끔하지가 않아서...
사실 수업을 준비한 리뷰어들끼리도 이를 어떻게 알려드려야할지 의견이 조금씩 갈렸습니다.
지금 제가 생각한 아이디어를 말씀드리면 2주 후에 있을 수업에 대한 스포일러 밖에 안될 것 같아서,
이 피드백은 제가 취소하도록 하겠습니다.

2023-10-20 11:51 UTC, ghojeong commented on src/main/java/persistence/entity/SimpleEntityManager.java
> +        }
지금은 이걸 해결하는게 무척 어렵다는 아쉬움을 남겨두고, 2주후에 있을 수업을 기대해주시면 좋을 것 같습니다!

2023-10-20 12:03 UTC, jongmin4943 commented on src/test/java/persistence/dialect/PersistenceEnvironmentStrategyTest.java
> +    }
[`bc2653b`](https://github.com/next-step/jpa-query-builder/pull/69/commits/bc2653b30203b3383606fd11003d7fac6a680107) - 완료

2023-10-20 12:04 UTC, jongmin4943 commented on src/main/java/persistence/dialect/OracleDialect.java
> +    }
[`eece203`](https://github.com/next-step/jpa-query-builder/pull/69/commits/eece203731de29ef4c404ef55420845bf7f278a3) - 완료

2023-10-20 12:04 UTC, jongmin4943 commented on src/test/java/persistence/ApplicationTest.java
> +        });
[`eb3558a`](https://github.com/next-step/jpa-query-builder/pull/69/commits/eb3558a516860ae013ed04831fe806e391b4e050) - 완료

2023-10-20 12:04 UTC, jongmin4943 commented on src/main/java/persistence/core/PersistenceEnvironmentStrategy.java
> +}
[`00a6698`](https://github.com/next-step/jpa-query-builder/pull/69/commits/00a6698e2b87a289872e2cfa7f5e4ccbef034aa9) - 완료

2023-10-20 12:05 UTC, jongmin4943 commented on src/main/java/persistence/dialect/H2Dialect.java
> +public class H2Dialect implements Dialect {
[`75ffda8`](https://github.com/next-step/jpa-query-builder/pull/69/commits/75ffda8a236690037fe523f195641e1a72487972) - 완료

2023-10-20 12:05 UTC, jongmin4943 commented
이번 1주차 리뷰 정말정말 감사합니다. 덕분에 재미있었습니다! 부족했지만 친절히 알려주셔서 이번 미션 잘 마무리 할 수 있었습니다. 이번 한 주가 어떻게 지나갔는지 모르겠네요 ㅎㅎ. 다음주 미션도 기대가 됩니다!

2023-10-21 00:34 UTC, ghojeong approved these changes
윤종민 님!
한주동안 미션 정말 고생 많으셨습니다.
저도 종민님과 함꼐 하며 즐거웠습니다.
다음주 미션도 화이팅이고, 완주하기를 기원하겠습니다!

2023-10-21 00:35 UTC, merged