Step3: DML
next-step/jpa-query-builder pull request #7
Opened 2023-06-15 16:12 UTC by ghojeong

안녕하세요!

Insert, FindAll, FindById, DeleteById
이렇게 4개의 작업에 대한 쿼리빌더를 구현헀습니다.

2023-06-17 11:04 UTC, liquidjoo requested changes
3단계 미션 구현 잘하셨어요 👍 
몇 가지 코멘트 남겼어요~
확인하고 다시 요청 주세요 🙇

2023-06-17 11:04 UTC, liquidjoo commented on src/main/java/persistence/sql/common/ColumnNames.java
> +public class ColumnNames {
`ColumnFields` 에 달린 코멘트 참고해주세요 :)

2023-06-17 11:04 UTC, liquidjoo commented on src/main/java/persistence/sql/common/ColumnValue.java
> +    }
해당 부분도 String 을 반환하고 View 를 위한 별도의 객체가 있어도 좋을 것 같아요 :)

2023-06-17 11:16 UTC, ghojeong commented on src/main/java/persistence/sql/common/ColumnValue.java
> +    }
common 이라고 패키지 명을 분류했던게, 사실은 다 view 로 분류되어야 할 것 같습니다.
패키지명을 view 라고 바꾸겠습니다.

2023-06-17 11:17 UTC, ghojeong commented on src/main/java/persistence/sql/common/ColumnFields.java
> +public class ColumnFields {
common 이 사실은 전부 view 라는 결론에 도달해서,
다 정적 팩토리만 남길 수 있도록 하겠습니다.

2023-06-17 15:46 UTC, ghojeong commented
static factory 메서드로 전부 통일하고,
의존성 주입을 제대로 활용하지는 못했지만, 그래도 최소한 dml 과 ddl 에 대해서 interface 를 선언해보았습니다.

2023-06-18 10:48 UTC, liquidjoo approved these changes
피드백 반영 좋습니다 👍 
1주 차 미션 고생하셨습니다~
2주 차 미션도 화이팅 입니다 😄

2023-06-18 10:48 UTC, liquidjoo commented on src/main/java/domain/Person.java
> +    public Person(Long id, String name, Integer age, String email, Integer index) {
생성자 활용 좋습니다 👍

2023-06-18 10:48 UTC, liquidjoo commented on src/main/java/persistence/sql/dialect/SqlDialect.java
> +public interface SqlDialect {
sql dialect ..!!
엄청난 추상화를 보여줄 수 있을 것 같군요

2023-06-18 10:48 UTC, liquidjoo commented on src/main/java/persistence/sql/dml/DmlBuilder.java
> +public interface DmlBuilder {
인터페이스에 하나 추가될 때 마다 구현체에서 계속 추가해 주어야하는 일이 발생할 것 같기도 하네요 😭

2023-06-18 10:48 UTC, liquidjoo commented on src/test/java/persistence/sql/dialect/h2/H2TypeDialectTest.java
> +class H2TypeDialectTest {
꼼꼼한 테스트 코드 👍

2023-06-18 10:48 UTC, liquidjoo commented on src/test/java/persistence/sql/dml/h2/H2DmlBuilderTest.java
> +class H2DmlBuilderTest {
꼼꼼한 테스트 코드 👍

2023-06-18 10:49 UTC, merged