SQL 쿼리 빌더 구현 3단계 - QueryBuilder DML 리뷰 요청입니다!
next-step/jpa-query-builder pull request #77
Opened 2023-10-20 14:11 UTC by profoundsea25

안녕하세요! 요한님.
step 3 구현이 완료되어 피드백 요청 드립니다.

step 2가 오래 걸렸던 이유가 어디까지 설계를 해야 하나...
현 버전의 JPA를 처음부터 만들려고 하다보니까 생각이 너무 많아져서,
지금 당장 주어진 요구사항에 집중하기로 하고 구현을 하고 있는데,
역시나 잘못된 설계들이 제 스스로도 느껴집니다...ㅎㅎ;

아무튼 지난 번 피드백과 더불어 insert, findAll, findById, delete 기능 구현하여 피드백 드립니다.
감사합니다.

2023-10-21 06:20 UTC, leeyohan93 requested changes
안녕하세요 해준님 😄
이번 단계도 잘 진행해주셨습니다 👍 
몇몇 코멘트들을 남겨두었으니 확인해보시고 고민이 되시는 부분 있다면 편하게 코멘트나 DM 남겨주세요 😄
오늘은 수업이 있는 날이네요 😄 
화이팅 입니다 🔥

2023-10-21 06:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/Query.java
> +}
Query로 인터페이스 명을 분리해주셨네요~! 👍 
다만 QueryBuilder 는 쿼리를 만드는 것이 주된 책임이라 생각하는데 Query에게 책임을 위임하다보니 
현재 로직에서는 모든 QueryBuilder 들 또한 별도의 구현체를 가져가는 것이 장점이 되지 않는 것 같습니다 🤔 
객체의 책임과 역할에 대해 고민해보시고, 과도하게 분리된 곳은 없는지 고민해보시면 좋을 것 같습니다 :)

2023-10-21 06:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/dialect/h2/H2DropQuery.java
> +public class H2DropQuery implements H2Dialect {
이전과 동일한 피드백입니다 :) 
https://github.com/next-step/jpa-query-builder/pull/63#discussion_r1365835177

추가적으로 H2Dialect 의 상수들은 H2 데이터베이스에 종속적인 쿼리 문법으로 보이지는 않는데요!
쿼리를 생성하는 입장에서 데이터베이스가 달라질 때 어떤 차이점을 가지는지에 대해 고민해보시면 좋을 것 같습니다 :)

2023-10-21 06:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/dialect/h2/H2Query.java
> +    private final H2DeleteQuery deleteQuery = new H2DeleteQuery();
현재 Query의 구현체는 의존성이 굉장히 많고 커다란 클래스가 된 것 같아 보입니다!
쿼리의 종류가 늘어날 수록 더더욱 코드가 커질 것을 예상되는데요 😢 

현재 구조에서는 QueryBuilder n개가 있다면 각 데이터베이스 마다 n개의 Query가 생기기 때문에 굉장히 많은 클래스들이 생겨나기 때문에 구조를 개선해보시면 좋을 것 같습니다 😄

2023-10-21 06:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/dml/FindByIdQueryBuilder.java
> +public class FindByIdQueryBuilder implements QueryBuilder {
다른 쿼리 빌더들과 다르게 findByIdQueryBuilder와 findAllQueryBuilder는 성격이 다른 것 같습니다! 🤔 
QueryBuilder를 나누는 기준에 대해 고민해보시면 좋을 것 같아요

2023-10-21 07:15 UTC, profoundsea25 commented on src/main/java/persistence/TestExecutions.java
> +public class TestExecutions {
직접 실행해서 확인해보려고 만든 클래스를 고민하다가 Test를 붙였어요..
Test를 떼고 그냥 Execution이라고 하면 어떤가요?
아니면 create나 drop을 테스트로 확인해볼 수 있는 걸 더 찾아보고, 테스트코드로 이동해보는게 더 나을까요?

2023-10-21 07:16 UTC, profoundsea25 commented on src/main/java/persistence/sql/QueryBuilder.java
> +    }
아하 넵 알겠습니다!!

2023-10-21 07:22 UTC, profoundsea25 commented on src/main/java/persistence/sql/Dialect.java
> +}
이거 고민입니다...
나중에 다른 클래스에 DI 할 때 생각해서 Dialect 타입이 필요할 것 같은데,
중간에 구조를 바꾸면서 메서드가 없는... 인터페이스가 되었어요.
일단 (위에서 상속을 위한 메서드를 없애면서) QueryBuilder와 Dialect 두 인터페이스가 어떠한 역할도 없는데,
일단 삭제해보겠습니다.

2023-10-21 07:22 UTC, profoundsea25 commented on src/test/java/persistence/sql/dml/InsertQueryBuilderTest.java
> +        );
넵 알겠습니다!

2023-10-21 07:36 UTC, profoundsea25 commented on src/main/java/persistence/sql/Query.java
> +}
정말요... QueryBuilder가 쓸모가 없어졌어요...
QueryBulider -> Query -> DB별 QueryBuilder 구조가 되었는데,
현재 QueryBuilder의 역할을 좀 바꿔보도록 하겠습니다.

2023-10-21 13:32 UTC, leeyohan93 commented on src/main/java/persistence/sql/Dialect.java
> +}
제가 생각할 때 이부분은 아래 피드백을 적용하면서 개선이 될 것 같아요.
https://github.com/next-step/jpa-query-builder/pull/77#discussion_r1367671576

이야기해주신 것처럼 QueryBuilder 와 Dialect 역할이 없다는건, 이 두 역할을 다른 곳에서 대신하고 있는 곳이 있다는 이야기인데요.
제 생각으로는 그게 바로 Query 인 것 같습니다 🤔  Query에서 두 객체에게 적절한 책임을 위임한다면 Query는 없어도 되는 클래스일 수도 있을 것 같아요!

2023-10-21 13:36 UTC, leeyohan93 commented on src/main/java/persistence/TestExecutions.java
> +public class TestExecutions {
직접 실행해보기 위한 테스트를 위해 만들어주셨군요~! 👍 
create나 drop을 별도로 테스트하기 위한 방법 까지는 찾지 않으셔도 될 것 같아요 :)
일단은 지금 임시로 유지하시고 다른 구조 개선에 포커싱을 두는 것이 좋을 것 같습니다! 🔥

2023-10-21 17:21 UTC, profoundsea25 commented on src/main/java/persistence/sql/dialect/h2/H2Query.java
> +    private final H2DeleteQuery deleteQuery = new H2DeleteQuery();
해당 클래스들 모두 삭제해버렸어요..!

2023-10-21 17:27 UTC, profoundsea25 commented
우선 Dialect마다 SQL이 극적으로 변할 수도 있겠다는 생각으로 크게 추상화를 하려다가 고민하는데 시간을 많이 썼군요 흑흑

주요 변경점은
- QueryBuilder 인터페이스 삭제
- H2에서 쿼리 만들던 클래스 삭제 (QueryBuilder와 역할이 중복된다고 판단)
- Query 인터페이스를 QueryBuilder의 파사드 형태로 변경
- Dialect에 DB별 타입정보를 포함
- SQL 표현들의 대부분을 QueryBuilder의 하드코딩으로 변경
- FindAllQueryBuilder, FindByIdQueryBuilder를 삭제, SelectQueryBuilder를 추가

변경해보았습니다..!
DB가 변경되면 어디까지 변해야 되는지 잘 예측이 안 되어서, 변화폭을 줄이는 선택을 했습니다..!

Query의 역할을 분담한다고 했는데, 저는 쿼리 빌더들을 조합하는 무언가가 있어야 하지 않나..? 해서 파사드 형태로 취급하였는데, 요한님이 생각하신 해당 인터페이스의 분리가 구체적으로 어떻게 구현되는지 궁금합니다!

2023-10-22 08:42 UTC, leeyohan93 approved these changes
안녕하세요 해준님 😄
이전 PR 이후에 많은 고민과 구조적인 개선에 너무 고생하셨습니다 👍 👍 
다음 단계로 넘어가기 이전에  고민하고 개선해보면 좋을 부분에 대해 코멘트 남겼으니 확인부탁드려요!
주말 동안도 고생 많으셨고 다음주도 화이팅입니다 🔥

2023-10-22 08:42 UTC, leeyohan93 commented on src/main/java/persistence/sql/dialect/h2/H2Query.java
> +    private static final H2Dialect dialect = new H2Dialect();
> Query의 역할을 분담한다고 했는데, 저는 쿼리 빌더들을 조합하는 무언가가 있어야 하지 않나..? 해서 파사드 형태로 취급하였는데, 요한님이 생각하신 해당 인터페이스의 분리가 구체적으로 어떻게 구현되는지 궁금합니다!

저도 해준님의 생각과 같이 쿼리 빌더들을 조합하는 무언가가 있어야한다고 생각합니다.
조금 스포하자면 다만 다음 미션인 `Entity 구현`에서 다루어질 부분이기 때문에 지금은 현재 단계에서는 요구사항에 맞춰 간단하게 구현하시는걸 추천드립니다 :)

만들어 주신 파사드 형태의 H2Query 이야기도 해보자면 Dialect의 추상화를 이용한다면
H2Query라는 구현체가 없더라도 H2Dialect을 주입하여 H2 에 적절한 쿼리 빌더들을 만들어낼 수 있을 것이라 생각됩니다!
아래 예시 처럼 구현한다면 굳이 데이터베이스 타입별로 Query의 구현체를 만들어내지 않아도 유연하게 사용할 수 있지 않을까요?
(현재 미션의 요구사항에서 벗어나기 때문에 지금 단계에서 아래와 같이 구현해달라고 요구하는 것은 아닙니다 😄 
오히려 지금은 덜어내는 것이 필요할 것 같아요)
```suggestion
public class QueryImpl {
    private Dialect dialect;
    
    public QueryImpl(Dialect dialect) {
        this.dialect = dialect
    }
```

2023-10-22 08:42 UTC, leeyohan93 commented on src/main/java/util/ReflectionUtil.java
> +    }
이전과 동일한 피드백입니다 :)
https://github.com/next-step/jpa-query-builder/pull/63#discussion_r1364215377

2023-10-22 08:42 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +        appendNotNullIfNeed(entityColumn, columnQueryPart);
컬럼의 제약조건들을 인터페이스로 추상화 해서 적용해보는건 어떨까요?
제약 조건들이 어떤 프로세스를 통해 공통적으로 적용되는지 고민해보시면 좋을 것 같습니다 :)

필수는 아니니 도전해보시고 싶으시다면 진행하셔도 괜찮습니다 :)

2023-10-22 08:42 UTC, leeyohan93 commented on src/main/java/persistence/sql/dialect/h2/H2Dialect.java
> +    }
다른 데이터베이스도 Dialect의 구현체를 만든다면 getStringLength()은 중복된 코드가 되지 않을까요? 🤔 
중복된 코드가 되지 않도록 개선해보면 좋을 것 같습니다

2023-10-22 08:43 UTC, merged

2023-10-23 11:21 UTC, profoundsea25 commented on src/main/java/persistence/sql/Dialect.java
> +    String INSERT_TEMPLATE = "insert into %s (%s) values (%s)";
개발하다보니... 일관성이 깨졌네요.
생각해보니 ON DUPLICATE KEY 같은 것 생각하면 저런 포맷팅 했으면 안 되었을 것 같네요;;
추가적으로 CREATE, DROP 정도는 스트링 포맷을 사용할 수 있겠군요
수정했습니다!

2023-10-23 11:22 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +                + ")";
넵 수정했습니다!

2023-10-23 11:26 UTC, profoundsea25 commented on src/main/java/persistence/sql/dialect/h2/H2Query.java
> +    private static final H2Dialect dialect = new H2Dialect();
오 피드백 감사드립니다! 슬쩍 바꿔보겠습니다 ㅎㅎ

2023-10-23 11:50 UTC, profoundsea25 commented on src/main/java/persistence/sql/dialect/h2/H2Dialect.java
> +    }
이런 상황에서 자주 상속(default 메서드) 혹은 유틸 클래스(static 클래스)를 사용했던 것 같네요.
조합으로 따로 빼보도록 하겠습니다!

2023-10-23 11:52 UTC, profoundsea25 commented on src/main/java/util/ReflectionUtil.java
> +    }
static이 아니라 해당 클래스를 Composition으로 받아 인스턴스 메서드를 사용하도록 해야 할까요?
리플렉션에서 값을 가져오는 보일러 플레이트라 따로 뺐는데, 의견이 궁금합니다!
아니면 쓰는 클래스마다 그냥 중복을 허용할까요?

2023-10-23 11:55 UTC, profoundsea25 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +        appendNotNullIfNeed(entityColumn, columnQueryPart);
컬럼들의 제약조건을 인터페이스로 추상화한다는 건, 예를들어 ```isNotNull()``` 같은 메서드를 말씀하시는 건가요?

2023-10-23 12:07 UTC, profoundsea25 commented
피드백 감사합니다!!

2023-10-24 12:11 UTC, leeyohan93 commented on src/main/java/persistence/sql/ddl/CreateQueryBuilder.java
> +        appendNotNullIfNeed(entityColumn, columnQueryPart);
네 맞습니다! :)

2023-10-24 12:12 UTC, leeyohan93 commented on src/main/java/util/ReflectionUtil.java
> +    }
두 가지 모두 방법이 될 수 있을 것 같습니다. 의도적인 중복을 허용할지, 객체에게 책임을 할당할 지 고민해보시면 좋을 것 같아요!