[Week1-Step3] QueryBuilder DML PR 리뷰 요청드립니다.
next-step/jpa-query-builder pull request #81
Opened 2023-10-21 01:35 UTC by NamKey

<img width="592" alt="image" src="https://github.com/next-step/jpa-query-builder/assets/25685282/5e96cf08-5d63-451e-a4de-e3d96403b6ea">

---

- DML을 생성하는 부분을 작성하며 EntityClassMappingMeta와 EntityObjectMappingMeta를 분리하여 DML에서는 Entity Object를 바탕으로 생성되도록 설계했습니다.
- Where 절이 Select와 Delete 생성에 재사용될 수 있는 구조로 설계했습니다.

---

- Where 절 / Where 절의 조건 / EntityObjectMappingMeta에 대한 테스트가 작성이 안되어 있는데 추가하도록 하겠습니다.

-- 

- findAll()/findById()는 어떤 방식으로 진행하면 될까요? 진행하다보니 스텝4를 진행하는 것 같아서 해당 부분 작업은 홀딩하고 있었습니다.

2023-10-21 12:20 UTC, leeyohan93 requested changes
안녕하세요 기륭님 😄
이번 단계에서는 여러가지 도전과 함께 너무 꼼꼼하게 잘 구현해주셨네요 🔥 
몇몇 코멘트들을 남겨두었으니 확인해보시고 고민이 되시는 부분 있다면 편하게 코멘트나 DM 남겨주세요 😄
오늘 하루도 수업 후에 미션까지 고생하셨습니다 🙏

2023-10-21 12:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +            }
null을 반환하게 되면 null check의 의무가 생기고 NPE가 발생할 가능성이 생기는데요.
null을 사용을 지양하는 쪽으로 개선해보면 어떨까요?

클린코드 - null을 반환하지 마라
http://amazingguni.github.io/blog/2016/05/Clean-Code-7-%EC%98%A4%EB%A5%98-%EC%B2%98%EB%A6%AC

2023-10-21 12:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
`And, OR` 과 `Equals, NotEqauls` 는 오퍼레이터의 성격이 다른 것 같다는 생각이 드는데 어떻게 생각하시나요?
SqlOpreator 추상화의 장점도 얻지 못하고 있는 것 같아요!

2023-10-21 12:20 UTC, leeyohan93 commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
클래스의 레이아웃을 아래와 같이 통일시켜주는건 어떠실까요 ? 😄 

```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2023-10-21 12:22 UTC, leeyohan93 commented
> findAll()/findById()는 어떤 방식으로 진행하면 될까요? 진행하다보니 스텝4를 진행하는 것 같아서 해당 부분 작업은 홀딩하고 있었습니다.

현재 단계에서는 테스트로 충분한 것 같습니다. 다음 주차의 단계에서 엔티티 매니저를 구현하시면서 직접적으로 호출하는 부분들을 만들게 되실 것 같아요! :)

2023-10-21 12:43 UTC, NamKey commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
해당 부분 같게 고민했던 부분입니다.
그래서 `ComparisonOperator` =, != 
`LogicalOperator` AND, OR

과 같이 분리를 진행하는 방식으로 고려를 하다가
1 AND 1/1 OR 1 은 하나의 조건식 내에서도 성립해야되지 않을까라는 생각까지 가서 하나의 인터페이스를 구현하도록 변경한 케이스였습니다.

이런 부분에서 어떻게 생각하실까요?

2023-10-22 07:22 UTC, NamKey commented on src/main/java/persistence/sql/schema/ValueMeta.java
> +public class ValueMeta {
Entity Instance의 값에 대한 로직들을 응집하기 위해서 새로 추가한 클래스입니다.

2023-10-22 07:22 UTC, NamKey commented on src/main/java/persistence/sql/schema/ValueMeta.java
> +            return null;
null은 SQL에서도 null로 표현해야 되서 null을 반환하도록 했습니다

2023-10-22 07:22 UTC, NamKey commented on src/main/java/persistence/sql/dml/statement/InsertStatementBuilder.java
> +            .filter(columnMeta -> !columnMeta.isPrimaryKey())
피드백 주셨던 부분이 공감가서 실제 쿼리를 만드는 부분에서
- PrimaryKey를 제외
- 필요한 정보들을 추출후 알맞게 포맷팅
하도록 수정했습니다.

2023-10-22 12:02 UTC, leeyohan93 commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
> 1 AND 1/1 OR 1 은 하나의 조건식 내에서도 성립해야되지 않을까
해당 부분에 대해서 제가 이해를 잘 못했는데 예시가 있을까요~?

2023-10-22 12:07 UTC, NamKey commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
실제로는 안티패턴이긴 한데 다음과 같은 경우의 수를 생각했습니다.
따라서 AND/OR과 Equals/NotEquals를 분리해버리면 예시와 같이 사용할 수 없으므로 모두 연산자(Operator)라는 인터페이스를 상속하게 했습니다.

``` SQL
WHERE (1 AND 1) AND (1 OR 1)
```

2023-10-22 12:15 UTC, leeyohan93 commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
아아 이해하였습니다~! 
제 개인적인 생각으로는 일반적인 저희가 자주 사용하는 쿼리의 형태로는 보이지 않아서 저라면 두 인터페이스를 나누고
저런 쿼리의 형태로 만드는 것을 지양하는 쪽으로 구현할 것 같습니다!
개인적인 의견이니 참고만 해주세요 :)

2023-10-22 12:29 UTC, NamKey commented on src/main/java/persistence/sql/dml/clause/builder/WhereClauseBuilder.java
> +    private static final OrOperator orOperator = new OrOperator();
말씀하신 것처럼 코드단에서 사용하지 못하게 제약하는 부분도 사용측면을 보더라도 명시적이여서 좋다는 생각이 드네요!
반영완료했습니다!

2023-10-22 14:41 UTC, leeyohan93 approved these changes
안녕하세요 기륭님 😄
피드백도 잘 적용해주시고 여러 고민을 해보시고 개선해주셔서 더욱 좋은 코드로 마무리된 것 같습니다! 💯 
몇몇 코멘트들을 남겨두었으니 확인해주시면 감사합니다 😄
이번 주도, 다음 스탭도 화이팅입니다 :)🔥

2023-10-22 14:41 UTC, leeyohan93 commented on src/main/java/persistence/sql/schema/ValueMeta.java
> +    public static String formatValueAsString(Object object) {
저는 개인적으로 static 메서드의 경우 유틸 클래스와 같은 단점을 지니고 있다고 생각하는데요!
WherePredicate가 ValueMeta를 의존성을 가지고 있는 부분도 조금 마음에 걸리네요 🤔 
의도적인 중복을 사용하거나 책임을 가진 객체를 만들어 구현해주시는 것도 좋을 것 같아요 :)

2023-10-22 14:41 UTC, leeyohan93 commented on src/main/java/persistence/sql/schema/ValueMeta.java
> +    }
현재는 ColumnMeta, ValueMeta 클래스들에서 쿼리를 만드는 기능을 일부 하고 있는 것 같은데요!
쿼리 생성에 대한 부분은 쿼리 빌더로 완전히 책임을 분리하는 것도 가능할 것 같습니다 :)

2023-10-22 14:42 UTC, merged

2023-10-22 16:26 UTC, NamKey commented on src/main/java/persistence/sql/schema/ValueMeta.java
> +    public static String formatValueAsString(Object object) {
피드백 주신 부분에 대해서 다시 생각해보니 의도적인 중복을 사용하는 부분으로도 마음이 기울기도 하는데 고민되는 포인트네요.
스텝 4 진행하면서 수정해보겠습니다!